module Evergreen.Migrate.V20 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V14.Types
import Evergreen.V20.Types
import Iso3166
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V14.Types.FrontendModel -> ModelMigration Evergreen.V20.Types.FrontendModel Evergreen.V20.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V14.Types.BackendModel -> ModelMigration Evergreen.V20.Types.BackendModel Evergreen.V20.Types.BackendMsg
backendModel _ =
    ModelUnchanged


frontendMsg : Evergreen.V14.Types.FrontendMsg -> MsgMigration Evergreen.V20.Types.FrontendMsg Evergreen.V20.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V14.Types.ToBackend -> MsgMigration Evergreen.V20.Types.ToBackend Evergreen.V20.Types.BackendMsg
toBackend _ =
    MsgUnchanged


backendMsg : Evergreen.V14.Types.BackendMsg -> MsgMigration Evergreen.V20.Types.BackendMsg Evergreen.V20.Types.BackendMsg
backendMsg _ =
    MsgUnchanged


toFrontend : Evergreen.V14.Types.ToFrontend -> MsgMigration Evergreen.V20.Types.ToFrontend Evergreen.V20.Types.FrontendMsg
toFrontend _ =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V14.Types.FrontendModel -> Evergreen.V20.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , context = old.context |> migrate_Types_Context
    , inner = old.inner |> migrate_Types_InnerModel
    , seed = old.seed
    }


migrate_Types_Card : Evergreen.V14.Types.Card -> Evergreen.V20.Types.Card
migrate_Types_Card old =
    { guessing = old.guessing |> migrate_Types_Country
    , answers = old.answers |> List.map migrate_Types_Country
    , guessFrom = old.guessFrom |> migrate_Types_Property
    , guessTo = old.guessTo |> migrate_Types_Property
    }


migrate_Types_Context : Evergreen.V14.Types.Context -> Evergreen.V20.Types.Context
migrate_Types_Context old =
    { language = old.language |> migrate_Types_Language
    }


migrate_Types_Country : Iso3166.CountryCode -> Evergreen.V20.Types.Country
migrate_Types_Country old =
    Evergreen.V20.Types.Iso3166 old


migrate_Types_Difficulty : Evergreen.V14.Types.Difficulty -> Evergreen.V20.Types.Difficulty
migrate_Types_Difficulty old =
    case old of
        Evergreen.V14.Types.Easy ->
            Evergreen.V20.Types.Easy

        Evergreen.V14.Types.Normal ->
            Evergreen.V20.Types.Normal

        Evergreen.V14.Types.Hard ->
            Evergreen.V20.Types.Hard


migrate_Types_FrontendMsg : Evergreen.V14.Types.FrontendMsg -> Evergreen.V20.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V14.Types.UrlClicked p0 ->
            Evergreen.V20.Types.UrlClicked p0

        Evergreen.V14.Types.UrlChanged p0 ->
            Evergreen.V20.Types.UrlChanged p0

        Evergreen.V14.Types.Play ->
            Evergreen.V20.Types.Play

        Evergreen.V14.Types.Seed p0 ->
            Evergreen.V20.Types.Seed p0

        Evergreen.V14.Types.Pick p0 ->
            Evergreen.V20.Types.Pick (p0 |> migrate_Types_Country)

        Evergreen.V14.Types.Next ->
            Evergreen.V20.Types.Next

        Evergreen.V14.Types.ChangeOptions p0 ->
            Evergreen.V20.Types.ChangeOptions (p0 |> migrate_Types_GameOptions)

        Evergreen.V14.Types.Move p0 p1 ->
            Evergreen.V20.Types.Move (p0 |> migrate_Types_Country) p1

        Evergreen.V14.Types.SelectForMove p0 ->
            Evergreen.V20.Types.SelectForMove (p0 |> migrate_Types_Country)


migrate_Types_GameOptions : Evergreen.V14.Types.GameOptions -> Evergreen.V20.Types.GameOptions
migrate_Types_GameOptions old =
    { gameLength = old.gameLength
    , difficulty = old.difficulty |> migrate_Types_Difficulty
    , answersPerCard = old.answersPerCard
    , guessPatterns = old.guessPatterns |> List.map (Tuple.mapBoth migrate_Types_Property migrate_Types_Property)
    , sovereignOnly = old.sovereignOnly
    }


migrate_Types_InnerModel : Evergreen.V14.Types.InnerModel -> Evergreen.V20.Types.InnerModel
migrate_Types_InnerModel old =
    case old of
        Evergreen.V14.Types.Homepage p0 ->
            Evergreen.V20.Types.Homepage (p0 |> migrate_Types_GameOptions)

        Evergreen.V14.Types.Playing p0 ->
            Evergreen.V20.Types.Playing (p0 |> migrate_Types_PlayingModel)

        Evergreen.V14.Types.Finished p0 ->
            Evergreen.V20.Types.Finished
                { options = p0.options |> migrate_Types_GameOptions
                , score = p0.score
                , total = p0.total
                }

        Evergreen.V14.Types.Sorting p0 ->
            Evergreen.V20.Types.Sorting (p0 |> migrate_Types_SortingModel)


migrate_Types_Language : Evergreen.V14.Types.Language -> Evergreen.V20.Types.Language
migrate_Types_Language old =
    case old of
        Evergreen.V14.Types.Arabic ->
            Evergreen.V20.Types.Arabic

        Evergreen.V14.Types.Chinese ->
            Evergreen.V20.Types.Chinese

        Evergreen.V14.Types.Czech ->
            Evergreen.V20.Types.Czech

        Evergreen.V14.Types.Danish ->
            Evergreen.V20.Types.Danish

        Evergreen.V14.Types.Dutch ->
            Evergreen.V20.Types.Dutch

        Evergreen.V14.Types.English ->
            Evergreen.V20.Types.English

        Evergreen.V14.Types.Estonian ->
            Evergreen.V20.Types.Estonian

        Evergreen.V14.Types.French ->
            Evergreen.V20.Types.French

        Evergreen.V14.Types.German ->
            Evergreen.V20.Types.German

        Evergreen.V14.Types.Greek ->
            Evergreen.V20.Types.Greek

        Evergreen.V14.Types.Hungarian ->
            Evergreen.V20.Types.Hungarian

        Evergreen.V14.Types.Italian ->
            Evergreen.V20.Types.Italian

        Evergreen.V14.Types.Japanese ->
            Evergreen.V20.Types.Japanese

        Evergreen.V14.Types.Lithuanian ->
            Evergreen.V20.Types.Lithuanian

        Evergreen.V14.Types.Norwegian ->
            Evergreen.V20.Types.Norwegian

        Evergreen.V14.Types.Polish ->
            Evergreen.V20.Types.Polish

        Evergreen.V14.Types.Portuguese ->
            Evergreen.V20.Types.Portuguese

        Evergreen.V14.Types.Romanian ->
            Evergreen.V20.Types.Romanian

        Evergreen.V14.Types.Russian ->
            Evergreen.V20.Types.Russian

        Evergreen.V14.Types.Slovak ->
            Evergreen.V20.Types.Slovak

        Evergreen.V14.Types.Spanish ->
            Evergreen.V20.Types.Spanish

        Evergreen.V14.Types.Thai ->
            Evergreen.V20.Types.Thai

        Evergreen.V14.Types.Ukrainian ->
            Evergreen.V20.Types.Ukrainian


migrate_Types_PlayingModel : Evergreen.V14.Types.PlayingModel -> Evergreen.V20.Types.PlayingModel
migrate_Types_PlayingModel old =
    { options = old.options |> migrate_Types_GameOptions
    , current = old.current |> migrate_Types_Card
    , picked = old.picked |> Maybe.map migrate_Types_Country
    , queue = old.queue |> List.map migrate_Types_Card
    , score = old.score
    }


migrate_Types_Property : Evergreen.V14.Types.Property -> Evergreen.V20.Types.Property
migrate_Types_Property old =
    case old of
        Evergreen.V14.Types.Flag ->
            Evergreen.V20.Types.Flag

        Evergreen.V14.Types.Name ->
            Evergreen.V20.Types.Name


migrate_Types_SortingModel : Evergreen.V14.Types.SortingModel -> Evergreen.V20.Types.SortingModel
migrate_Types_SortingModel old =
    { groups = old.groups |> List.map (List.map migrate_Types_Country)
    , selected = old.selected |> Maybe.map migrate_Types_Country
    }
