module Evergreen.Migrate.V25 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V24.Cldr
import Evergreen.V24.Types
import Evergreen.V25.Cldr
import Evergreen.V25.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V24.Types.FrontendModel -> ModelMigration Evergreen.V25.Types.FrontendModel Evergreen.V25.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V24.Types.BackendModel -> ModelMigration Evergreen.V25.Types.BackendModel Evergreen.V25.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V24.Types.FrontendMsg -> MsgMigration Evergreen.V25.Types.FrontendMsg Evergreen.V25.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V24.Types.ToBackend -> MsgMigration Evergreen.V25.Types.ToBackend Evergreen.V25.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V24.Types.BackendMsg -> MsgMigration Evergreen.V25.Types.BackendMsg Evergreen.V25.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V24.Types.ToFrontend -> MsgMigration Evergreen.V25.Types.ToFrontend Evergreen.V25.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V24.Types.FrontendModel -> Evergreen.V25.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , context = old.context |> migrate_Types_Context
    , changingLocale = Nothing
    , inner = old.inner |> migrate_Types_InnerModel
    , seed = old.seed
    }


migrate_Cldr_CountryCode : Evergreen.V24.Cldr.CountryCode -> Evergreen.V25.Cldr.CountryCode
migrate_Cldr_CountryCode old =
    case old of
        Evergreen.V24.Cldr.AD ->
            Evergreen.V25.Cldr.AD

        Evergreen.V24.Cldr.AE ->
            Evergreen.V25.Cldr.AE

        Evergreen.V24.Cldr.AF ->
            Evergreen.V25.Cldr.AF

        Evergreen.V24.Cldr.AG ->
            Evergreen.V25.Cldr.AG

        Evergreen.V24.Cldr.AI ->
            Evergreen.V25.Cldr.AI

        Evergreen.V24.Cldr.AL ->
            Evergreen.V25.Cldr.AL

        Evergreen.V24.Cldr.AM ->
            Evergreen.V25.Cldr.AM

        Evergreen.V24.Cldr.AO ->
            Evergreen.V25.Cldr.AO

        Evergreen.V24.Cldr.AQ ->
            Evergreen.V25.Cldr.AQ

        Evergreen.V24.Cldr.AR ->
            Evergreen.V25.Cldr.AR

        Evergreen.V24.Cldr.AS ->
            Evergreen.V25.Cldr.AS

        Evergreen.V24.Cldr.AT ->
            Evergreen.V25.Cldr.AT

        Evergreen.V24.Cldr.AU ->
            Evergreen.V25.Cldr.AU

        Evergreen.V24.Cldr.AW ->
            Evergreen.V25.Cldr.AW

        Evergreen.V24.Cldr.AX ->
            Evergreen.V25.Cldr.AX

        Evergreen.V24.Cldr.AZ ->
            Evergreen.V25.Cldr.AZ

        Evergreen.V24.Cldr.BA ->
            Evergreen.V25.Cldr.BA

        Evergreen.V24.Cldr.BB ->
            Evergreen.V25.Cldr.BB

        Evergreen.V24.Cldr.BD ->
            Evergreen.V25.Cldr.BD

        Evergreen.V24.Cldr.BE ->
            Evergreen.V25.Cldr.BE

        Evergreen.V24.Cldr.BF ->
            Evergreen.V25.Cldr.BF

        Evergreen.V24.Cldr.BG ->
            Evergreen.V25.Cldr.BG

        Evergreen.V24.Cldr.BH ->
            Evergreen.V25.Cldr.BH

        Evergreen.V24.Cldr.BI ->
            Evergreen.V25.Cldr.BI

        Evergreen.V24.Cldr.BJ ->
            Evergreen.V25.Cldr.BJ

        Evergreen.V24.Cldr.BL ->
            Evergreen.V25.Cldr.BL

        Evergreen.V24.Cldr.BM ->
            Evergreen.V25.Cldr.BM

        Evergreen.V24.Cldr.BN ->
            Evergreen.V25.Cldr.BN

        Evergreen.V24.Cldr.BO ->
            Evergreen.V25.Cldr.BO

        Evergreen.V24.Cldr.BQ ->
            Evergreen.V25.Cldr.BQ

        Evergreen.V24.Cldr.BR ->
            Evergreen.V25.Cldr.BR

        Evergreen.V24.Cldr.BS ->
            Evergreen.V25.Cldr.BS

        Evergreen.V24.Cldr.BT ->
            Evergreen.V25.Cldr.BT

        Evergreen.V24.Cldr.BV ->
            Evergreen.V25.Cldr.BV

        Evergreen.V24.Cldr.BW ->
            Evergreen.V25.Cldr.BW

        Evergreen.V24.Cldr.BY ->
            Evergreen.V25.Cldr.BY

        Evergreen.V24.Cldr.BZ ->
            Evergreen.V25.Cldr.BZ

        Evergreen.V24.Cldr.CA ->
            Evergreen.V25.Cldr.CA

        Evergreen.V24.Cldr.CC ->
            Evergreen.V25.Cldr.CC

        Evergreen.V24.Cldr.CD ->
            Evergreen.V25.Cldr.CD

        Evergreen.V24.Cldr.CF ->
            Evergreen.V25.Cldr.CF

        Evergreen.V24.Cldr.CG ->
            Evergreen.V25.Cldr.CG

        Evergreen.V24.Cldr.CH ->
            Evergreen.V25.Cldr.CH

        Evergreen.V24.Cldr.CI ->
            Evergreen.V25.Cldr.CI

        Evergreen.V24.Cldr.CK ->
            Evergreen.V25.Cldr.CK

        Evergreen.V24.Cldr.CL ->
            Evergreen.V25.Cldr.CL

        Evergreen.V24.Cldr.CM ->
            Evergreen.V25.Cldr.CM

        Evergreen.V24.Cldr.CN ->
            Evergreen.V25.Cldr.CN

        Evergreen.V24.Cldr.CO ->
            Evergreen.V25.Cldr.CO

        Evergreen.V24.Cldr.CR ->
            Evergreen.V25.Cldr.CR

        Evergreen.V24.Cldr.CU ->
            Evergreen.V25.Cldr.CU

        Evergreen.V24.Cldr.CV ->
            Evergreen.V25.Cldr.CV

        Evergreen.V24.Cldr.CW ->
            Evergreen.V25.Cldr.CW

        Evergreen.V24.Cldr.CX ->
            Evergreen.V25.Cldr.CX

        Evergreen.V24.Cldr.CY ->
            Evergreen.V25.Cldr.CY

        Evergreen.V24.Cldr.CZ ->
            Evergreen.V25.Cldr.CZ

        Evergreen.V24.Cldr.DE ->
            Evergreen.V25.Cldr.DE

        Evergreen.V24.Cldr.DJ ->
            Evergreen.V25.Cldr.DJ

        Evergreen.V24.Cldr.DK ->
            Evergreen.V25.Cldr.DK

        Evergreen.V24.Cldr.DM ->
            Evergreen.V25.Cldr.DM

        Evergreen.V24.Cldr.DO ->
            Evergreen.V25.Cldr.DO

        Evergreen.V24.Cldr.DZ ->
            Evergreen.V25.Cldr.DZ

        Evergreen.V24.Cldr.EC ->
            Evergreen.V25.Cldr.EC

        Evergreen.V24.Cldr.EE ->
            Evergreen.V25.Cldr.EE

        Evergreen.V24.Cldr.EG ->
            Evergreen.V25.Cldr.EG

        Evergreen.V24.Cldr.EH ->
            Evergreen.V25.Cldr.EH

        Evergreen.V24.Cldr.ER ->
            Evergreen.V25.Cldr.ER

        Evergreen.V24.Cldr.ES ->
            Evergreen.V25.Cldr.ES

        Evergreen.V24.Cldr.ET ->
            Evergreen.V25.Cldr.ET

        Evergreen.V24.Cldr.FI ->
            Evergreen.V25.Cldr.FI

        Evergreen.V24.Cldr.FJ ->
            Evergreen.V25.Cldr.FJ

        Evergreen.V24.Cldr.FK ->
            Evergreen.V25.Cldr.FK

        Evergreen.V24.Cldr.FM ->
            Evergreen.V25.Cldr.FM

        Evergreen.V24.Cldr.FO ->
            Evergreen.V25.Cldr.FO

        Evergreen.V24.Cldr.FR ->
            Evergreen.V25.Cldr.FR

        Evergreen.V24.Cldr.GA ->
            Evergreen.V25.Cldr.GA

        Evergreen.V24.Cldr.GB ->
            Evergreen.V25.Cldr.GB

        Evergreen.V24.Cldr.GD ->
            Evergreen.V25.Cldr.GD

        Evergreen.V24.Cldr.GE ->
            Evergreen.V25.Cldr.GE

        Evergreen.V24.Cldr.GF ->
            Evergreen.V25.Cldr.GF

        Evergreen.V24.Cldr.GG ->
            Evergreen.V25.Cldr.GG

        Evergreen.V24.Cldr.GH ->
            Evergreen.V25.Cldr.GH

        Evergreen.V24.Cldr.GI ->
            Evergreen.V25.Cldr.GI

        Evergreen.V24.Cldr.GL ->
            Evergreen.V25.Cldr.GL

        Evergreen.V24.Cldr.GM ->
            Evergreen.V25.Cldr.GM

        Evergreen.V24.Cldr.GN ->
            Evergreen.V25.Cldr.GN

        Evergreen.V24.Cldr.GP ->
            Evergreen.V25.Cldr.GP

        Evergreen.V24.Cldr.GQ ->
            Evergreen.V25.Cldr.GQ

        Evergreen.V24.Cldr.GR ->
            Evergreen.V25.Cldr.GR

        Evergreen.V24.Cldr.GS ->
            Evergreen.V25.Cldr.GS

        Evergreen.V24.Cldr.GT_ ->
            Evergreen.V25.Cldr.GT_

        Evergreen.V24.Cldr.GU ->
            Evergreen.V25.Cldr.GU

        Evergreen.V24.Cldr.GW ->
            Evergreen.V25.Cldr.GW

        Evergreen.V24.Cldr.GY ->
            Evergreen.V25.Cldr.GY

        Evergreen.V24.Cldr.HK ->
            Evergreen.V25.Cldr.HK

        Evergreen.V24.Cldr.HM ->
            Evergreen.V25.Cldr.HM

        Evergreen.V24.Cldr.HN ->
            Evergreen.V25.Cldr.HN

        Evergreen.V24.Cldr.HR ->
            Evergreen.V25.Cldr.HR

        Evergreen.V24.Cldr.HT ->
            Evergreen.V25.Cldr.HT

        Evergreen.V24.Cldr.HU ->
            Evergreen.V25.Cldr.HU

        Evergreen.V24.Cldr.ID ->
            Evergreen.V25.Cldr.ID

        Evergreen.V24.Cldr.IE ->
            Evergreen.V25.Cldr.IE

        Evergreen.V24.Cldr.IL ->
            Evergreen.V25.Cldr.IL

        Evergreen.V24.Cldr.IM ->
            Evergreen.V25.Cldr.IM

        Evergreen.V24.Cldr.IN ->
            Evergreen.V25.Cldr.IN

        Evergreen.V24.Cldr.IO ->
            Evergreen.V25.Cldr.IO

        Evergreen.V24.Cldr.IQ ->
            Evergreen.V25.Cldr.IQ

        Evergreen.V24.Cldr.IR ->
            Evergreen.V25.Cldr.IR

        Evergreen.V24.Cldr.IS ->
            Evergreen.V25.Cldr.IS

        Evergreen.V24.Cldr.IT ->
            Evergreen.V25.Cldr.IT

        Evergreen.V24.Cldr.JE ->
            Evergreen.V25.Cldr.JE

        Evergreen.V24.Cldr.JM ->
            Evergreen.V25.Cldr.JM

        Evergreen.V24.Cldr.JO ->
            Evergreen.V25.Cldr.JO

        Evergreen.V24.Cldr.JP ->
            Evergreen.V25.Cldr.JP

        Evergreen.V24.Cldr.KE ->
            Evergreen.V25.Cldr.KE

        Evergreen.V24.Cldr.KG ->
            Evergreen.V25.Cldr.KG

        Evergreen.V24.Cldr.KH ->
            Evergreen.V25.Cldr.KH

        Evergreen.V24.Cldr.KI ->
            Evergreen.V25.Cldr.KI

        Evergreen.V24.Cldr.KM ->
            Evergreen.V25.Cldr.KM

        Evergreen.V24.Cldr.KN ->
            Evergreen.V25.Cldr.KN

        Evergreen.V24.Cldr.KP ->
            Evergreen.V25.Cldr.KP

        Evergreen.V24.Cldr.KR ->
            Evergreen.V25.Cldr.KR

        Evergreen.V24.Cldr.KW ->
            Evergreen.V25.Cldr.KW

        Evergreen.V24.Cldr.KY ->
            Evergreen.V25.Cldr.KY

        Evergreen.V24.Cldr.KZ ->
            Evergreen.V25.Cldr.KZ

        Evergreen.V24.Cldr.LA ->
            Evergreen.V25.Cldr.LA

        Evergreen.V24.Cldr.LB ->
            Evergreen.V25.Cldr.LB

        Evergreen.V24.Cldr.LC ->
            Evergreen.V25.Cldr.LC

        Evergreen.V24.Cldr.LI ->
            Evergreen.V25.Cldr.LI

        Evergreen.V24.Cldr.LK ->
            Evergreen.V25.Cldr.LK

        Evergreen.V24.Cldr.LR ->
            Evergreen.V25.Cldr.LR

        Evergreen.V24.Cldr.LS ->
            Evergreen.V25.Cldr.LS

        Evergreen.V24.Cldr.LT_ ->
            Evergreen.V25.Cldr.LT_

        Evergreen.V24.Cldr.LU ->
            Evergreen.V25.Cldr.LU

        Evergreen.V24.Cldr.LV ->
            Evergreen.V25.Cldr.LV

        Evergreen.V24.Cldr.LY ->
            Evergreen.V25.Cldr.LY

        Evergreen.V24.Cldr.MA ->
            Evergreen.V25.Cldr.MA

        Evergreen.V24.Cldr.MC ->
            Evergreen.V25.Cldr.MC

        Evergreen.V24.Cldr.MD ->
            Evergreen.V25.Cldr.MD

        Evergreen.V24.Cldr.ME ->
            Evergreen.V25.Cldr.ME

        Evergreen.V24.Cldr.MF ->
            Evergreen.V25.Cldr.MF

        Evergreen.V24.Cldr.MG ->
            Evergreen.V25.Cldr.MG

        Evergreen.V24.Cldr.MH ->
            Evergreen.V25.Cldr.MH

        Evergreen.V24.Cldr.MK ->
            Evergreen.V25.Cldr.MK

        Evergreen.V24.Cldr.ML ->
            Evergreen.V25.Cldr.ML

        Evergreen.V24.Cldr.MM ->
            Evergreen.V25.Cldr.MM

        Evergreen.V24.Cldr.MN ->
            Evergreen.V25.Cldr.MN

        Evergreen.V24.Cldr.MO ->
            Evergreen.V25.Cldr.MO

        Evergreen.V24.Cldr.MP ->
            Evergreen.V25.Cldr.MP

        Evergreen.V24.Cldr.MQ ->
            Evergreen.V25.Cldr.MQ

        Evergreen.V24.Cldr.MR ->
            Evergreen.V25.Cldr.MR

        Evergreen.V24.Cldr.MS ->
            Evergreen.V25.Cldr.MS

        Evergreen.V24.Cldr.MT ->
            Evergreen.V25.Cldr.MT

        Evergreen.V24.Cldr.MU ->
            Evergreen.V25.Cldr.MU

        Evergreen.V24.Cldr.MV ->
            Evergreen.V25.Cldr.MV

        Evergreen.V24.Cldr.MW ->
            Evergreen.V25.Cldr.MW

        Evergreen.V24.Cldr.MX ->
            Evergreen.V25.Cldr.MX

        Evergreen.V24.Cldr.MY ->
            Evergreen.V25.Cldr.MY

        Evergreen.V24.Cldr.MZ ->
            Evergreen.V25.Cldr.MZ

        Evergreen.V24.Cldr.NA ->
            Evergreen.V25.Cldr.NA

        Evergreen.V24.Cldr.NC ->
            Evergreen.V25.Cldr.NC

        Evergreen.V24.Cldr.NE ->
            Evergreen.V25.Cldr.NE

        Evergreen.V24.Cldr.NF ->
            Evergreen.V25.Cldr.NF

        Evergreen.V24.Cldr.NG ->
            Evergreen.V25.Cldr.NG

        Evergreen.V24.Cldr.NI ->
            Evergreen.V25.Cldr.NI

        Evergreen.V24.Cldr.NL ->
            Evergreen.V25.Cldr.NL

        Evergreen.V24.Cldr.NO ->
            Evergreen.V25.Cldr.NO

        Evergreen.V24.Cldr.NP ->
            Evergreen.V25.Cldr.NP

        Evergreen.V24.Cldr.NR ->
            Evergreen.V25.Cldr.NR

        Evergreen.V24.Cldr.NU ->
            Evergreen.V25.Cldr.NU

        Evergreen.V24.Cldr.NZ ->
            Evergreen.V25.Cldr.NZ

        Evergreen.V24.Cldr.OM ->
            Evergreen.V25.Cldr.OM

        Evergreen.V24.Cldr.PA ->
            Evergreen.V25.Cldr.PA

        Evergreen.V24.Cldr.PE ->
            Evergreen.V25.Cldr.PE

        Evergreen.V24.Cldr.PF ->
            Evergreen.V25.Cldr.PF

        Evergreen.V24.Cldr.PG ->
            Evergreen.V25.Cldr.PG

        Evergreen.V24.Cldr.PH ->
            Evergreen.V25.Cldr.PH

        Evergreen.V24.Cldr.PK ->
            Evergreen.V25.Cldr.PK

        Evergreen.V24.Cldr.PL ->
            Evergreen.V25.Cldr.PL

        Evergreen.V24.Cldr.PM ->
            Evergreen.V25.Cldr.PM

        Evergreen.V24.Cldr.PN ->
            Evergreen.V25.Cldr.PN

        Evergreen.V24.Cldr.PR ->
            Evergreen.V25.Cldr.PR

        Evergreen.V24.Cldr.PS ->
            Evergreen.V25.Cldr.PS

        Evergreen.V24.Cldr.PT ->
            Evergreen.V25.Cldr.PT

        Evergreen.V24.Cldr.PW ->
            Evergreen.V25.Cldr.PW

        Evergreen.V24.Cldr.PY ->
            Evergreen.V25.Cldr.PY

        Evergreen.V24.Cldr.QA ->
            Evergreen.V25.Cldr.QA

        Evergreen.V24.Cldr.RE ->
            Evergreen.V25.Cldr.RE

        Evergreen.V24.Cldr.RO ->
            Evergreen.V25.Cldr.RO

        Evergreen.V24.Cldr.RS ->
            Evergreen.V25.Cldr.RS

        Evergreen.V24.Cldr.RU ->
            Evergreen.V25.Cldr.RU

        Evergreen.V24.Cldr.RW ->
            Evergreen.V25.Cldr.RW

        Evergreen.V24.Cldr.SA ->
            Evergreen.V25.Cldr.SA

        Evergreen.V24.Cldr.SB ->
            Evergreen.V25.Cldr.SB

        Evergreen.V24.Cldr.SC ->
            Evergreen.V25.Cldr.SC

        Evergreen.V24.Cldr.SD ->
            Evergreen.V25.Cldr.SD

        Evergreen.V24.Cldr.SE ->
            Evergreen.V25.Cldr.SE

        Evergreen.V24.Cldr.SG ->
            Evergreen.V25.Cldr.SG

        Evergreen.V24.Cldr.SH ->
            Evergreen.V25.Cldr.SH

        Evergreen.V24.Cldr.SI ->
            Evergreen.V25.Cldr.SI

        Evergreen.V24.Cldr.SJ ->
            Evergreen.V25.Cldr.SJ

        Evergreen.V24.Cldr.SK ->
            Evergreen.V25.Cldr.SK

        Evergreen.V24.Cldr.SL ->
            Evergreen.V25.Cldr.SL

        Evergreen.V24.Cldr.SM ->
            Evergreen.V25.Cldr.SM

        Evergreen.V24.Cldr.SN ->
            Evergreen.V25.Cldr.SN

        Evergreen.V24.Cldr.SO ->
            Evergreen.V25.Cldr.SO

        Evergreen.V24.Cldr.SR ->
            Evergreen.V25.Cldr.SR

        Evergreen.V24.Cldr.SS ->
            Evergreen.V25.Cldr.SS

        Evergreen.V24.Cldr.ST ->
            Evergreen.V25.Cldr.ST

        Evergreen.V24.Cldr.SV ->
            Evergreen.V25.Cldr.SV

        Evergreen.V24.Cldr.SX ->
            Evergreen.V25.Cldr.SX

        Evergreen.V24.Cldr.SY ->
            Evergreen.V25.Cldr.SY

        Evergreen.V24.Cldr.SZ ->
            Evergreen.V25.Cldr.SZ

        Evergreen.V24.Cldr.TC ->
            Evergreen.V25.Cldr.TC

        Evergreen.V24.Cldr.TD ->
            Evergreen.V25.Cldr.TD

        Evergreen.V24.Cldr.TF ->
            Evergreen.V25.Cldr.TF

        Evergreen.V24.Cldr.TG ->
            Evergreen.V25.Cldr.TG

        Evergreen.V24.Cldr.TH ->
            Evergreen.V25.Cldr.TH

        Evergreen.V24.Cldr.TJ ->
            Evergreen.V25.Cldr.TJ

        Evergreen.V24.Cldr.TK ->
            Evergreen.V25.Cldr.TK

        Evergreen.V24.Cldr.TL ->
            Evergreen.V25.Cldr.TL

        Evergreen.V24.Cldr.TM ->
            Evergreen.V25.Cldr.TM

        Evergreen.V24.Cldr.TN ->
            Evergreen.V25.Cldr.TN

        Evergreen.V24.Cldr.TO ->
            Evergreen.V25.Cldr.TO

        Evergreen.V24.Cldr.TR ->
            Evergreen.V25.Cldr.TR

        Evergreen.V24.Cldr.TT ->
            Evergreen.V25.Cldr.TT

        Evergreen.V24.Cldr.TV ->
            Evergreen.V25.Cldr.TV

        Evergreen.V24.Cldr.TW ->
            Evergreen.V25.Cldr.TW

        Evergreen.V24.Cldr.TZ ->
            Evergreen.V25.Cldr.TZ

        Evergreen.V24.Cldr.UA ->
            Evergreen.V25.Cldr.UA

        Evergreen.V24.Cldr.UG ->
            Evergreen.V25.Cldr.UG

        Evergreen.V24.Cldr.UM ->
            Evergreen.V25.Cldr.UM

        Evergreen.V24.Cldr.US ->
            Evergreen.V25.Cldr.US

        Evergreen.V24.Cldr.UY ->
            Evergreen.V25.Cldr.UY

        Evergreen.V24.Cldr.UZ ->
            Evergreen.V25.Cldr.UZ

        Evergreen.V24.Cldr.VA ->
            Evergreen.V25.Cldr.VA

        Evergreen.V24.Cldr.VC ->
            Evergreen.V25.Cldr.VC

        Evergreen.V24.Cldr.VE ->
            Evergreen.V25.Cldr.VE

        Evergreen.V24.Cldr.VG ->
            Evergreen.V25.Cldr.VG

        Evergreen.V24.Cldr.VI ->
            Evergreen.V25.Cldr.VI

        Evergreen.V24.Cldr.VN ->
            Evergreen.V25.Cldr.VN

        Evergreen.V24.Cldr.VU ->
            Evergreen.V25.Cldr.VU

        Evergreen.V24.Cldr.WF ->
            Evergreen.V25.Cldr.WF

        Evergreen.V24.Cldr.WS ->
            Evergreen.V25.Cldr.WS

        Evergreen.V24.Cldr.XK ->
            Evergreen.V25.Cldr.XK

        Evergreen.V24.Cldr.YE ->
            Evergreen.V25.Cldr.YE

        Evergreen.V24.Cldr.YT ->
            Evergreen.V25.Cldr.YT

        Evergreen.V24.Cldr.ZA ->
            Evergreen.V25.Cldr.ZA

        Evergreen.V24.Cldr.ZM ->
            Evergreen.V25.Cldr.ZM

        Evergreen.V24.Cldr.ZW ->
            Evergreen.V25.Cldr.ZW


migrate_Types_Card : Evergreen.V24.Types.Card -> Evergreen.V25.Types.Card
migrate_Types_Card old =
    { guessing = old.guessing |> migrate_Types_Country
    , answers = old.answers |> List.map migrate_Types_Country
    , guessFrom = old.guessFrom |> migrate_Types_Property
    , guessTo = old.guessTo |> migrate_Types_Property
    }


migrate_Types_Context : Evergreen.V24.Types.Context -> Evergreen.V25.Types.Context
migrate_Types_Context old =
    { locale = Evergreen.V25.Cldr.En
    }


migrate_Types_Country : Evergreen.V24.Types.Country -> Evergreen.V25.Types.Country
migrate_Types_Country old =
    case old of
        Evergreen.V24.Types.Iso3166 p0 ->
            Evergreen.V25.Types.Iso3166 (p0 |> migrate_Cldr_CountryCode)

        Evergreen.V24.Types.PartiallyRecognized p0 ->
            Evergreen.V25.Types.PartiallyRecognized p0


migrate_Types_Difficulty : Evergreen.V24.Types.Difficulty -> Evergreen.V25.Types.Difficulty
migrate_Types_Difficulty old =
    case old of
        Evergreen.V24.Types.Easy ->
            Evergreen.V25.Types.Easy

        Evergreen.V24.Types.Normal ->
            Evergreen.V25.Types.Normal

        Evergreen.V24.Types.Hard ->
            Evergreen.V25.Types.Hard


migrate_Types_FrontendMsg : Evergreen.V24.Types.FrontendMsg -> Evergreen.V25.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V24.Types.UrlClicked p0 ->
            Evergreen.V25.Types.UrlClicked p0

        Evergreen.V24.Types.UrlChanged p0 ->
            Evergreen.V25.Types.UrlChanged p0

        Evergreen.V24.Types.Play ->
            Evergreen.V25.Types.Play

        Evergreen.V24.Types.Seed p0 ->
            Evergreen.V25.Types.Seed p0

        Evergreen.V24.Types.Pick p0 ->
            Evergreen.V25.Types.Pick (p0 |> migrate_Types_Country)

        Evergreen.V24.Types.Next ->
            Evergreen.V25.Types.Next

        Evergreen.V24.Types.ChangeOptions p0 ->
            Evergreen.V25.Types.ChangeOptions (p0 |> migrate_Types_GameOptions)

        Evergreen.V24.Types.Move p0 p1 ->
            Evergreen.V25.Types.Move (p0 |> migrate_Types_Country) p1

        Evergreen.V24.Types.SelectForMove p0 ->
            Evergreen.V25.Types.SelectForMove (p0 |> migrate_Types_Country)



migrate_Types_GameOptions : Evergreen.V24.Types.GameOptions -> Evergreen.V25.Types.GameOptions
migrate_Types_GameOptions old =
    { gameLength = old.gameLength
    , difficulty = old.difficulty |> migrate_Types_Difficulty
    , answersPerCard = old.answersPerCard
    , guessPatterns = old.guessPatterns |> List.map (Tuple.mapBoth migrate_Types_Property migrate_Types_Property)
    , sovereignOnly = old.sovereignOnly
    }


migrate_Types_InnerModel : Evergreen.V24.Types.InnerModel -> Evergreen.V25.Types.InnerModel
migrate_Types_InnerModel old =
    case old of
        Evergreen.V24.Types.Homepage p0 ->
            Evergreen.V25.Types.Homepage (p0 |> migrate_Types_GameOptions)

        Evergreen.V24.Types.Playing p0 ->
            Evergreen.V25.Types.Playing (p0 |> migrate_Types_PlayingModel)

        Evergreen.V24.Types.Finished p0 ->
            Evergreen.V25.Types.Finished
                { options = p0.options |> migrate_Types_GameOptions
                , score = p0.score
                , total = p0.total
                }

        Evergreen.V24.Types.Sorting p0 ->
            Evergreen.V25.Types.Sorting (p0 |> migrate_Types_SortingModel)


migrate_Types_PlayingModel : Evergreen.V24.Types.PlayingModel -> Evergreen.V25.Types.PlayingModel
migrate_Types_PlayingModel old =
    { options = old.options |> migrate_Types_GameOptions
    , current = old.current |> migrate_Types_Card
    , picked = old.picked |> Maybe.map migrate_Types_Country
    , queue = old.queue |> List.map migrate_Types_Card
    , score = old.score
    }


migrate_Types_Property : Evergreen.V24.Types.Property -> Evergreen.V25.Types.Property
migrate_Types_Property old =
    case old of
        Evergreen.V24.Types.Flag ->
            Evergreen.V25.Types.Flag

        Evergreen.V24.Types.Name ->
            Evergreen.V25.Types.Name


migrate_Types_SortingModel : Evergreen.V24.Types.SortingModel -> Evergreen.V25.Types.SortingModel
migrate_Types_SortingModel old =
    { groups = old.groups |> List.map (List.map migrate_Types_Country)
    , selected = old.selected |> Maybe.map migrate_Types_Country
    }
