module Evergreen.Migrate.V31 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V25.Cldr
import Evergreen.V25.Types
import Evergreen.V31.Cldr
import Evergreen.V31.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V25.Types.FrontendModel -> ModelMigration Evergreen.V31.Types.FrontendModel Evergreen.V31.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V25.Types.BackendModel -> ModelMigration Evergreen.V31.Types.BackendModel Evergreen.V31.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V25.Types.FrontendMsg -> MsgMigration Evergreen.V31.Types.FrontendMsg Evergreen.V31.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V25.Types.ToBackend -> MsgMigration Evergreen.V31.Types.ToBackend Evergreen.V31.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V25.Types.BackendMsg -> MsgMigration Evergreen.V31.Types.BackendMsg Evergreen.V31.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V25.Types.ToFrontend -> MsgMigration Evergreen.V31.Types.ToFrontend Evergreen.V31.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Cldr_CountryCode : Evergreen.V25.Cldr.CountryCode -> Evergreen.V31.Cldr.CountryCode
migrate_Cldr_CountryCode old =
    case old of
        Evergreen.V25.Cldr.AD ->
            Evergreen.V31.Cldr.AD

        Evergreen.V25.Cldr.AE ->
            Evergreen.V31.Cldr.AE

        Evergreen.V25.Cldr.AF ->
            Evergreen.V31.Cldr.AF

        Evergreen.V25.Cldr.AG ->
            Evergreen.V31.Cldr.AG

        Evergreen.V25.Cldr.AI ->
            Evergreen.V31.Cldr.AI

        Evergreen.V25.Cldr.AL ->
            Evergreen.V31.Cldr.AL

        Evergreen.V25.Cldr.AM ->
            Evergreen.V31.Cldr.AM

        Evergreen.V25.Cldr.AO ->
            Evergreen.V31.Cldr.AO

        Evergreen.V25.Cldr.AQ ->
            Evergreen.V31.Cldr.AQ

        Evergreen.V25.Cldr.AR ->
            Evergreen.V31.Cldr.AR

        Evergreen.V25.Cldr.AS ->
            Evergreen.V31.Cldr.AS

        Evergreen.V25.Cldr.AT ->
            Evergreen.V31.Cldr.AT

        Evergreen.V25.Cldr.AU ->
            Evergreen.V31.Cldr.AU

        Evergreen.V25.Cldr.AW ->
            Evergreen.V31.Cldr.AW

        Evergreen.V25.Cldr.AX ->
            Evergreen.V31.Cldr.AX

        Evergreen.V25.Cldr.AZ ->
            Evergreen.V31.Cldr.AZ

        Evergreen.V25.Cldr.BA ->
            Evergreen.V31.Cldr.BA

        Evergreen.V25.Cldr.BB ->
            Evergreen.V31.Cldr.BB

        Evergreen.V25.Cldr.BD ->
            Evergreen.V31.Cldr.BD

        Evergreen.V25.Cldr.BE ->
            Evergreen.V31.Cldr.BE

        Evergreen.V25.Cldr.BF ->
            Evergreen.V31.Cldr.BF

        Evergreen.V25.Cldr.BG ->
            Evergreen.V31.Cldr.BG

        Evergreen.V25.Cldr.BH ->
            Evergreen.V31.Cldr.BH

        Evergreen.V25.Cldr.BI ->
            Evergreen.V31.Cldr.BI

        Evergreen.V25.Cldr.BJ ->
            Evergreen.V31.Cldr.BJ

        Evergreen.V25.Cldr.BL ->
            Evergreen.V31.Cldr.BL

        Evergreen.V25.Cldr.BM ->
            Evergreen.V31.Cldr.BM

        Evergreen.V25.Cldr.BN ->
            Evergreen.V31.Cldr.BN

        Evergreen.V25.Cldr.BO ->
            Evergreen.V31.Cldr.BO

        Evergreen.V25.Cldr.BQ ->
            Evergreen.V31.Cldr.BQ

        Evergreen.V25.Cldr.BR ->
            Evergreen.V31.Cldr.BR

        Evergreen.V25.Cldr.BS ->
            Evergreen.V31.Cldr.BS

        Evergreen.V25.Cldr.BT ->
            Evergreen.V31.Cldr.BT

        Evergreen.V25.Cldr.BV ->
            Evergreen.V31.Cldr.BV

        Evergreen.V25.Cldr.BW ->
            Evergreen.V31.Cldr.BW

        Evergreen.V25.Cldr.BY ->
            Evergreen.V31.Cldr.BY

        Evergreen.V25.Cldr.BZ ->
            Evergreen.V31.Cldr.BZ

        Evergreen.V25.Cldr.CA ->
            Evergreen.V31.Cldr.CA

        Evergreen.V25.Cldr.CC ->
            Evergreen.V31.Cldr.CC

        Evergreen.V25.Cldr.CD ->
            Evergreen.V31.Cldr.CD

        Evergreen.V25.Cldr.CF ->
            Evergreen.V31.Cldr.CF

        Evergreen.V25.Cldr.CG ->
            Evergreen.V31.Cldr.CG

        Evergreen.V25.Cldr.CH ->
            Evergreen.V31.Cldr.CH

        Evergreen.V25.Cldr.CI ->
            Evergreen.V31.Cldr.CI

        Evergreen.V25.Cldr.CK ->
            Evergreen.V31.Cldr.CK

        Evergreen.V25.Cldr.CL ->
            Evergreen.V31.Cldr.CL

        Evergreen.V25.Cldr.CM ->
            Evergreen.V31.Cldr.CM

        Evergreen.V25.Cldr.CN ->
            Evergreen.V31.Cldr.CN

        Evergreen.V25.Cldr.CO ->
            Evergreen.V31.Cldr.CO

        Evergreen.V25.Cldr.CR ->
            Evergreen.V31.Cldr.CR

        Evergreen.V25.Cldr.CU ->
            Evergreen.V31.Cldr.CU

        Evergreen.V25.Cldr.CV ->
            Evergreen.V31.Cldr.CV

        Evergreen.V25.Cldr.CW ->
            Evergreen.V31.Cldr.CW

        Evergreen.V25.Cldr.CX ->
            Evergreen.V31.Cldr.CX

        Evergreen.V25.Cldr.CY ->
            Evergreen.V31.Cldr.CY

        Evergreen.V25.Cldr.CZ ->
            Evergreen.V31.Cldr.CZ

        Evergreen.V25.Cldr.DE ->
            Evergreen.V31.Cldr.DE

        Evergreen.V25.Cldr.DJ ->
            Evergreen.V31.Cldr.DJ

        Evergreen.V25.Cldr.DK ->
            Evergreen.V31.Cldr.DK

        Evergreen.V25.Cldr.DM ->
            Evergreen.V31.Cldr.DM

        Evergreen.V25.Cldr.DO ->
            Evergreen.V31.Cldr.DO

        Evergreen.V25.Cldr.DZ ->
            Evergreen.V31.Cldr.DZ

        Evergreen.V25.Cldr.EC ->
            Evergreen.V31.Cldr.EC

        Evergreen.V25.Cldr.EE ->
            Evergreen.V31.Cldr.EE

        Evergreen.V25.Cldr.EG ->
            Evergreen.V31.Cldr.EG

        Evergreen.V25.Cldr.EH ->
            Evergreen.V31.Cldr.EH

        Evergreen.V25.Cldr.ER ->
            Evergreen.V31.Cldr.ER

        Evergreen.V25.Cldr.ES ->
            Evergreen.V31.Cldr.ES

        Evergreen.V25.Cldr.ET ->
            Evergreen.V31.Cldr.ET

        Evergreen.V25.Cldr.FI ->
            Evergreen.V31.Cldr.FI

        Evergreen.V25.Cldr.FJ ->
            Evergreen.V31.Cldr.FJ

        Evergreen.V25.Cldr.FK ->
            Evergreen.V31.Cldr.FK

        Evergreen.V25.Cldr.FM ->
            Evergreen.V31.Cldr.FM

        Evergreen.V25.Cldr.FO ->
            Evergreen.V31.Cldr.FO

        Evergreen.V25.Cldr.FR ->
            Evergreen.V31.Cldr.FR

        Evergreen.V25.Cldr.GA ->
            Evergreen.V31.Cldr.GA

        Evergreen.V25.Cldr.GB ->
            Evergreen.V31.Cldr.GB

        Evergreen.V25.Cldr.GD ->
            Evergreen.V31.Cldr.GD

        Evergreen.V25.Cldr.GE ->
            Evergreen.V31.Cldr.GE

        Evergreen.V25.Cldr.GF ->
            Evergreen.V31.Cldr.GF

        Evergreen.V25.Cldr.GG ->
            Evergreen.V31.Cldr.GG

        Evergreen.V25.Cldr.GH ->
            Evergreen.V31.Cldr.GH

        Evergreen.V25.Cldr.GI ->
            Evergreen.V31.Cldr.GI

        Evergreen.V25.Cldr.GL ->
            Evergreen.V31.Cldr.GL

        Evergreen.V25.Cldr.GM ->
            Evergreen.V31.Cldr.GM

        Evergreen.V25.Cldr.GN ->
            Evergreen.V31.Cldr.GN

        Evergreen.V25.Cldr.GP ->
            Evergreen.V31.Cldr.GP

        Evergreen.V25.Cldr.GQ ->
            Evergreen.V31.Cldr.GQ

        Evergreen.V25.Cldr.GR ->
            Evergreen.V31.Cldr.GR

        Evergreen.V25.Cldr.GS ->
            Evergreen.V31.Cldr.GS

        Evergreen.V25.Cldr.GT_ ->
            Evergreen.V31.Cldr.GT_

        Evergreen.V25.Cldr.GU ->
            Evergreen.V31.Cldr.GU

        Evergreen.V25.Cldr.GW ->
            Evergreen.V31.Cldr.GW

        Evergreen.V25.Cldr.GY ->
            Evergreen.V31.Cldr.GY

        Evergreen.V25.Cldr.HK ->
            Evergreen.V31.Cldr.HK

        Evergreen.V25.Cldr.HM ->
            Evergreen.V31.Cldr.HM

        Evergreen.V25.Cldr.HN ->
            Evergreen.V31.Cldr.HN

        Evergreen.V25.Cldr.HR ->
            Evergreen.V31.Cldr.HR

        Evergreen.V25.Cldr.HT ->
            Evergreen.V31.Cldr.HT

        Evergreen.V25.Cldr.HU ->
            Evergreen.V31.Cldr.HU

        Evergreen.V25.Cldr.ID ->
            Evergreen.V31.Cldr.ID

        Evergreen.V25.Cldr.IE ->
            Evergreen.V31.Cldr.IE

        Evergreen.V25.Cldr.IL ->
            Evergreen.V31.Cldr.IL

        Evergreen.V25.Cldr.IM ->
            Evergreen.V31.Cldr.IM

        Evergreen.V25.Cldr.IN ->
            Evergreen.V31.Cldr.IN

        Evergreen.V25.Cldr.IO ->
            Evergreen.V31.Cldr.IO

        Evergreen.V25.Cldr.IQ ->
            Evergreen.V31.Cldr.IQ

        Evergreen.V25.Cldr.IR ->
            Evergreen.V31.Cldr.IR

        Evergreen.V25.Cldr.IS ->
            Evergreen.V31.Cldr.IS

        Evergreen.V25.Cldr.IT ->
            Evergreen.V31.Cldr.IT

        Evergreen.V25.Cldr.JE ->
            Evergreen.V31.Cldr.JE

        Evergreen.V25.Cldr.JM ->
            Evergreen.V31.Cldr.JM

        Evergreen.V25.Cldr.JO ->
            Evergreen.V31.Cldr.JO

        Evergreen.V25.Cldr.JP ->
            Evergreen.V31.Cldr.JP

        Evergreen.V25.Cldr.KE ->
            Evergreen.V31.Cldr.KE

        Evergreen.V25.Cldr.KG ->
            Evergreen.V31.Cldr.KG

        Evergreen.V25.Cldr.KH ->
            Evergreen.V31.Cldr.KH

        Evergreen.V25.Cldr.KI ->
            Evergreen.V31.Cldr.KI

        Evergreen.V25.Cldr.KM ->
            Evergreen.V31.Cldr.KM

        Evergreen.V25.Cldr.KN ->
            Evergreen.V31.Cldr.KN

        Evergreen.V25.Cldr.KP ->
            Evergreen.V31.Cldr.KP

        Evergreen.V25.Cldr.KR ->
            Evergreen.V31.Cldr.KR

        Evergreen.V25.Cldr.KW ->
            Evergreen.V31.Cldr.KW

        Evergreen.V25.Cldr.KY ->
            Evergreen.V31.Cldr.KY

        Evergreen.V25.Cldr.KZ ->
            Evergreen.V31.Cldr.KZ

        Evergreen.V25.Cldr.LA ->
            Evergreen.V31.Cldr.LA

        Evergreen.V25.Cldr.LB ->
            Evergreen.V31.Cldr.LB

        Evergreen.V25.Cldr.LC ->
            Evergreen.V31.Cldr.LC

        Evergreen.V25.Cldr.LI ->
            Evergreen.V31.Cldr.LI

        Evergreen.V25.Cldr.LK ->
            Evergreen.V31.Cldr.LK

        Evergreen.V25.Cldr.LR ->
            Evergreen.V31.Cldr.LR

        Evergreen.V25.Cldr.LS ->
            Evergreen.V31.Cldr.LS

        Evergreen.V25.Cldr.LT_ ->
            Evergreen.V31.Cldr.LT_

        Evergreen.V25.Cldr.LU ->
            Evergreen.V31.Cldr.LU

        Evergreen.V25.Cldr.LV ->
            Evergreen.V31.Cldr.LV

        Evergreen.V25.Cldr.LY ->
            Evergreen.V31.Cldr.LY

        Evergreen.V25.Cldr.MA ->
            Evergreen.V31.Cldr.MA

        Evergreen.V25.Cldr.MC ->
            Evergreen.V31.Cldr.MC

        Evergreen.V25.Cldr.MD ->
            Evergreen.V31.Cldr.MD

        Evergreen.V25.Cldr.ME ->
            Evergreen.V31.Cldr.ME

        Evergreen.V25.Cldr.MF ->
            Evergreen.V31.Cldr.MF

        Evergreen.V25.Cldr.MG ->
            Evergreen.V31.Cldr.MG

        Evergreen.V25.Cldr.MH ->
            Evergreen.V31.Cldr.MH

        Evergreen.V25.Cldr.MK ->
            Evergreen.V31.Cldr.MK

        Evergreen.V25.Cldr.ML ->
            Evergreen.V31.Cldr.ML

        Evergreen.V25.Cldr.MM ->
            Evergreen.V31.Cldr.MM

        Evergreen.V25.Cldr.MN ->
            Evergreen.V31.Cldr.MN

        Evergreen.V25.Cldr.MO ->
            Evergreen.V31.Cldr.MO

        Evergreen.V25.Cldr.MP ->
            Evergreen.V31.Cldr.MP

        Evergreen.V25.Cldr.MQ ->
            Evergreen.V31.Cldr.MQ

        Evergreen.V25.Cldr.MR ->
            Evergreen.V31.Cldr.MR

        Evergreen.V25.Cldr.MS ->
            Evergreen.V31.Cldr.MS

        Evergreen.V25.Cldr.MT ->
            Evergreen.V31.Cldr.MT

        Evergreen.V25.Cldr.MU ->
            Evergreen.V31.Cldr.MU

        Evergreen.V25.Cldr.MV ->
            Evergreen.V31.Cldr.MV

        Evergreen.V25.Cldr.MW ->
            Evergreen.V31.Cldr.MW

        Evergreen.V25.Cldr.MX ->
            Evergreen.V31.Cldr.MX

        Evergreen.V25.Cldr.MY ->
            Evergreen.V31.Cldr.MY

        Evergreen.V25.Cldr.MZ ->
            Evergreen.V31.Cldr.MZ

        Evergreen.V25.Cldr.NA ->
            Evergreen.V31.Cldr.NA

        Evergreen.V25.Cldr.NC ->
            Evergreen.V31.Cldr.NC

        Evergreen.V25.Cldr.NE ->
            Evergreen.V31.Cldr.NE

        Evergreen.V25.Cldr.NF ->
            Evergreen.V31.Cldr.NF

        Evergreen.V25.Cldr.NG ->
            Evergreen.V31.Cldr.NG

        Evergreen.V25.Cldr.NI ->
            Evergreen.V31.Cldr.NI

        Evergreen.V25.Cldr.NL ->
            Evergreen.V31.Cldr.NL

        Evergreen.V25.Cldr.NO ->
            Evergreen.V31.Cldr.NO

        Evergreen.V25.Cldr.NP ->
            Evergreen.V31.Cldr.NP

        Evergreen.V25.Cldr.NR ->
            Evergreen.V31.Cldr.NR

        Evergreen.V25.Cldr.NU ->
            Evergreen.V31.Cldr.NU

        Evergreen.V25.Cldr.NZ ->
            Evergreen.V31.Cldr.NZ

        Evergreen.V25.Cldr.OM ->
            Evergreen.V31.Cldr.OM

        Evergreen.V25.Cldr.PA ->
            Evergreen.V31.Cldr.PA

        Evergreen.V25.Cldr.PE ->
            Evergreen.V31.Cldr.PE

        Evergreen.V25.Cldr.PF ->
            Evergreen.V31.Cldr.PF

        Evergreen.V25.Cldr.PG ->
            Evergreen.V31.Cldr.PG

        Evergreen.V25.Cldr.PH ->
            Evergreen.V31.Cldr.PH

        Evergreen.V25.Cldr.PK ->
            Evergreen.V31.Cldr.PK

        Evergreen.V25.Cldr.PL ->
            Evergreen.V31.Cldr.PL

        Evergreen.V25.Cldr.PM ->
            Evergreen.V31.Cldr.PM

        Evergreen.V25.Cldr.PN ->
            Evergreen.V31.Cldr.PN

        Evergreen.V25.Cldr.PR ->
            Evergreen.V31.Cldr.PR

        Evergreen.V25.Cldr.PS ->
            Evergreen.V31.Cldr.PS

        Evergreen.V25.Cldr.PT ->
            Evergreen.V31.Cldr.PT

        Evergreen.V25.Cldr.PW ->
            Evergreen.V31.Cldr.PW

        Evergreen.V25.Cldr.PY ->
            Evergreen.V31.Cldr.PY

        Evergreen.V25.Cldr.QA ->
            Evergreen.V31.Cldr.QA

        Evergreen.V25.Cldr.RE ->
            Evergreen.V31.Cldr.RE

        Evergreen.V25.Cldr.RO ->
            Evergreen.V31.Cldr.RO

        Evergreen.V25.Cldr.RS ->
            Evergreen.V31.Cldr.RS

        Evergreen.V25.Cldr.RU ->
            Evergreen.V31.Cldr.RU

        Evergreen.V25.Cldr.RW ->
            Evergreen.V31.Cldr.RW

        Evergreen.V25.Cldr.SA ->
            Evergreen.V31.Cldr.SA

        Evergreen.V25.Cldr.SB ->
            Evergreen.V31.Cldr.SB

        Evergreen.V25.Cldr.SC ->
            Evergreen.V31.Cldr.SC

        Evergreen.V25.Cldr.SD ->
            Evergreen.V31.Cldr.SD

        Evergreen.V25.Cldr.SE ->
            Evergreen.V31.Cldr.SE

        Evergreen.V25.Cldr.SG ->
            Evergreen.V31.Cldr.SG

        Evergreen.V25.Cldr.SH ->
            Evergreen.V31.Cldr.SH

        Evergreen.V25.Cldr.SI ->
            Evergreen.V31.Cldr.SI

        Evergreen.V25.Cldr.SJ ->
            Evergreen.V31.Cldr.SJ

        Evergreen.V25.Cldr.SK ->
            Evergreen.V31.Cldr.SK

        Evergreen.V25.Cldr.SL ->
            Evergreen.V31.Cldr.SL

        Evergreen.V25.Cldr.SM ->
            Evergreen.V31.Cldr.SM

        Evergreen.V25.Cldr.SN ->
            Evergreen.V31.Cldr.SN

        Evergreen.V25.Cldr.SO ->
            Evergreen.V31.Cldr.SO

        Evergreen.V25.Cldr.SR ->
            Evergreen.V31.Cldr.SR

        Evergreen.V25.Cldr.SS ->
            Evergreen.V31.Cldr.SS

        Evergreen.V25.Cldr.ST ->
            Evergreen.V31.Cldr.ST

        Evergreen.V25.Cldr.SV ->
            Evergreen.V31.Cldr.SV

        Evergreen.V25.Cldr.SX ->
            Evergreen.V31.Cldr.SX

        Evergreen.V25.Cldr.SY ->
            Evergreen.V31.Cldr.SY

        Evergreen.V25.Cldr.SZ ->
            Evergreen.V31.Cldr.SZ

        Evergreen.V25.Cldr.TC ->
            Evergreen.V31.Cldr.TC

        Evergreen.V25.Cldr.TD ->
            Evergreen.V31.Cldr.TD

        Evergreen.V25.Cldr.TF ->
            Evergreen.V31.Cldr.TF

        Evergreen.V25.Cldr.TG ->
            Evergreen.V31.Cldr.TG

        Evergreen.V25.Cldr.TH ->
            Evergreen.V31.Cldr.TH

        Evergreen.V25.Cldr.TJ ->
            Evergreen.V31.Cldr.TJ

        Evergreen.V25.Cldr.TK ->
            Evergreen.V31.Cldr.TK

        Evergreen.V25.Cldr.TL ->
            Evergreen.V31.Cldr.TL

        Evergreen.V25.Cldr.TM ->
            Evergreen.V31.Cldr.TM

        Evergreen.V25.Cldr.TN ->
            Evergreen.V31.Cldr.TN

        Evergreen.V25.Cldr.TO ->
            Evergreen.V31.Cldr.TO

        Evergreen.V25.Cldr.TR ->
            Evergreen.V31.Cldr.TR

        Evergreen.V25.Cldr.TT ->
            Evergreen.V31.Cldr.TT

        Evergreen.V25.Cldr.TV ->
            Evergreen.V31.Cldr.TV

        Evergreen.V25.Cldr.TW ->
            Evergreen.V31.Cldr.TW

        Evergreen.V25.Cldr.TZ ->
            Evergreen.V31.Cldr.TZ

        Evergreen.V25.Cldr.UA ->
            Evergreen.V31.Cldr.UA

        Evergreen.V25.Cldr.UG ->
            Evergreen.V31.Cldr.UG

        Evergreen.V25.Cldr.UM ->
            Evergreen.V31.Cldr.UM

        Evergreen.V25.Cldr.US ->
            Evergreen.V31.Cldr.US

        Evergreen.V25.Cldr.UY ->
            Evergreen.V31.Cldr.UY

        Evergreen.V25.Cldr.UZ ->
            Evergreen.V31.Cldr.UZ

        Evergreen.V25.Cldr.VA ->
            Evergreen.V31.Cldr.VA

        Evergreen.V25.Cldr.VC ->
            Evergreen.V31.Cldr.VC

        Evergreen.V25.Cldr.VE ->
            Evergreen.V31.Cldr.VE

        Evergreen.V25.Cldr.VG ->
            Evergreen.V31.Cldr.VG

        Evergreen.V25.Cldr.VI ->
            Evergreen.V31.Cldr.VI

        Evergreen.V25.Cldr.VN ->
            Evergreen.V31.Cldr.VN

        Evergreen.V25.Cldr.VU ->
            Evergreen.V31.Cldr.VU

        Evergreen.V25.Cldr.WF ->
            Evergreen.V31.Cldr.WF

        Evergreen.V25.Cldr.WS ->
            Evergreen.V31.Cldr.WS

        Evergreen.V25.Cldr.XK ->
            Evergreen.V31.Cldr.XK

        Evergreen.V25.Cldr.YE ->
            Evergreen.V31.Cldr.YE

        Evergreen.V25.Cldr.YT ->
            Evergreen.V31.Cldr.YT

        Evergreen.V25.Cldr.ZA ->
            Evergreen.V31.Cldr.ZA

        Evergreen.V25.Cldr.ZM ->
            Evergreen.V31.Cldr.ZM

        Evergreen.V25.Cldr.ZW ->
            Evergreen.V31.Cldr.ZW


migrate_Cldr_Locale : Evergreen.V25.Cldr.Locale -> Evergreen.V31.Cldr.Locale
migrate_Cldr_Locale old =
    case old of
        Evergreen.V25.Cldr.Af ->
            Evergreen.V31.Cldr.Af

        Evergreen.V25.Cldr.AfNA ->
            Evergreen.V31.Cldr.AfNA

        Evergreen.V25.Cldr.Am ->
            Evergreen.V31.Cldr.Am

        Evergreen.V25.Cldr.Ar ->
            Evergreen.V31.Cldr.Ar

        Evergreen.V25.Cldr.ArAE ->
            Evergreen.V31.Cldr.ArAE

        Evergreen.V25.Cldr.ArBH ->
            Evergreen.V31.Cldr.ArBH

        Evergreen.V25.Cldr.ArDJ ->
            Evergreen.V31.Cldr.ArDJ

        Evergreen.V25.Cldr.ArDZ ->
            Evergreen.V31.Cldr.ArDZ

        Evergreen.V25.Cldr.ArEG ->
            Evergreen.V31.Cldr.ArEG

        Evergreen.V25.Cldr.ArEH ->
            Evergreen.V31.Cldr.ArEH

        Evergreen.V25.Cldr.ArER ->
            Evergreen.V31.Cldr.ArER

        Evergreen.V25.Cldr.ArIL ->
            Evergreen.V31.Cldr.ArIL

        Evergreen.V25.Cldr.ArIQ ->
            Evergreen.V31.Cldr.ArIQ

        Evergreen.V25.Cldr.ArJO ->
            Evergreen.V31.Cldr.ArJO

        Evergreen.V25.Cldr.ArKM ->
            Evergreen.V31.Cldr.ArKM

        Evergreen.V25.Cldr.ArKW ->
            Evergreen.V31.Cldr.ArKW

        Evergreen.V25.Cldr.ArLB ->
            Evergreen.V31.Cldr.ArLB

        Evergreen.V25.Cldr.ArLY ->
            Evergreen.V31.Cldr.ArLY

        Evergreen.V25.Cldr.ArMA ->
            Evergreen.V31.Cldr.ArMA

        Evergreen.V25.Cldr.ArMR ->
            Evergreen.V31.Cldr.ArMR

        Evergreen.V25.Cldr.ArOM ->
            Evergreen.V31.Cldr.ArOM

        Evergreen.V25.Cldr.ArPS ->
            Evergreen.V31.Cldr.ArPS

        Evergreen.V25.Cldr.ArQA ->
            Evergreen.V31.Cldr.ArQA

        Evergreen.V25.Cldr.ArSA ->
            Evergreen.V31.Cldr.ArSA

        Evergreen.V25.Cldr.ArSD ->
            Evergreen.V31.Cldr.ArSD

        Evergreen.V25.Cldr.ArSO ->
            Evergreen.V31.Cldr.ArSO

        Evergreen.V25.Cldr.ArSS ->
            Evergreen.V31.Cldr.ArSS

        Evergreen.V25.Cldr.ArSY ->
            Evergreen.V31.Cldr.ArSY

        Evergreen.V25.Cldr.ArTD ->
            Evergreen.V31.Cldr.ArTD

        Evergreen.V25.Cldr.ArTN ->
            Evergreen.V31.Cldr.ArTN

        Evergreen.V25.Cldr.ArYE ->
            Evergreen.V31.Cldr.ArYE

        Evergreen.V25.Cldr.As ->
            Evergreen.V31.Cldr.As

        Evergreen.V25.Cldr.Az ->
            Evergreen.V31.Cldr.Az

        Evergreen.V25.Cldr.AzLatn ->
            Evergreen.V31.Cldr.AzLatn

        Evergreen.V25.Cldr.Be ->
            Evergreen.V31.Cldr.Be

        Evergreen.V25.Cldr.BeTarask ->
            Evergreen.V31.Cldr.BeTarask

        Evergreen.V25.Cldr.Bg ->
            Evergreen.V31.Cldr.Bg

        Evergreen.V25.Cldr.Bn ->
            Evergreen.V31.Cldr.Bn

        Evergreen.V25.Cldr.BnIN ->
            Evergreen.V31.Cldr.BnIN

        Evergreen.V25.Cldr.Bs ->
            Evergreen.V31.Cldr.Bs

        Evergreen.V25.Cldr.BsLatn ->
            Evergreen.V31.Cldr.BsLatn

        Evergreen.V25.Cldr.Ca ->
            Evergreen.V31.Cldr.Ca

        Evergreen.V25.Cldr.CaAD ->
            Evergreen.V31.Cldr.CaAD

        Evergreen.V25.Cldr.CaESValencia ->
            Evergreen.V31.Cldr.CaESValencia

        Evergreen.V25.Cldr.CaFR ->
            Evergreen.V31.Cldr.CaFR

        Evergreen.V25.Cldr.CaIT ->
            Evergreen.V31.Cldr.CaIT

        Evergreen.V25.Cldr.Cs ->
            Evergreen.V31.Cldr.Cs

        Evergreen.V25.Cldr.Cy ->
            Evergreen.V31.Cldr.Cy

        Evergreen.V25.Cldr.Da ->
            Evergreen.V31.Cldr.Da

        Evergreen.V25.Cldr.DaGL ->
            Evergreen.V31.Cldr.DaGL

        Evergreen.V25.Cldr.De ->
            Evergreen.V31.Cldr.De

        Evergreen.V25.Cldr.DeAT ->
            Evergreen.V31.Cldr.DeAT

        Evergreen.V25.Cldr.DeBE ->
            Evergreen.V31.Cldr.DeBE

        Evergreen.V25.Cldr.DeCH ->
            Evergreen.V31.Cldr.DeCH

        Evergreen.V25.Cldr.DeIT ->
            Evergreen.V31.Cldr.DeIT

        Evergreen.V25.Cldr.DeLI ->
            Evergreen.V31.Cldr.DeLI

        Evergreen.V25.Cldr.DeLU ->
            Evergreen.V31.Cldr.DeLU

        Evergreen.V25.Cldr.El ->
            Evergreen.V31.Cldr.El

        Evergreen.V25.Cldr.ElCY ->
            Evergreen.V31.Cldr.ElCY

        Evergreen.V25.Cldr.ElPolyton ->
            Evergreen.V31.Cldr.ElPolyton

        Evergreen.V25.Cldr.En ->
            Evergreen.V31.Cldr.En

        Evergreen.V25.Cldr.En001 ->
            Evergreen.V31.Cldr.En001

        Evergreen.V25.Cldr.En150 ->
            Evergreen.V31.Cldr.En150

        Evergreen.V25.Cldr.EnAE ->
            Evergreen.V31.Cldr.EnAE

        Evergreen.V25.Cldr.EnAG ->
            Evergreen.V31.Cldr.EnAG

        Evergreen.V25.Cldr.EnAI ->
            Evergreen.V31.Cldr.EnAI

        Evergreen.V25.Cldr.EnAS ->
            Evergreen.V31.Cldr.EnAS

        Evergreen.V25.Cldr.EnAT ->
            Evergreen.V31.Cldr.EnAT

        Evergreen.V25.Cldr.EnAU ->
            Evergreen.V31.Cldr.EnAU

        Evergreen.V25.Cldr.EnBB ->
            Evergreen.V31.Cldr.EnBB

        Evergreen.V25.Cldr.EnBE ->
            Evergreen.V31.Cldr.EnBE

        Evergreen.V25.Cldr.EnBI ->
            Evergreen.V31.Cldr.EnBI

        Evergreen.V25.Cldr.EnBM ->
            Evergreen.V31.Cldr.EnBM

        Evergreen.V25.Cldr.EnBS ->
            Evergreen.V31.Cldr.EnBS

        Evergreen.V25.Cldr.EnBW ->
            Evergreen.V31.Cldr.EnBW

        Evergreen.V25.Cldr.EnBZ ->
            Evergreen.V31.Cldr.EnBZ

        Evergreen.V25.Cldr.EnCA ->
            Evergreen.V31.Cldr.EnCA

        Evergreen.V25.Cldr.EnCC ->
            Evergreen.V31.Cldr.EnCC

        Evergreen.V25.Cldr.EnCH ->
            Evergreen.V31.Cldr.EnCH

        Evergreen.V25.Cldr.EnCK ->
            Evergreen.V31.Cldr.EnCK

        Evergreen.V25.Cldr.EnCM ->
            Evergreen.V31.Cldr.EnCM

        Evergreen.V25.Cldr.EnCX ->
            Evergreen.V31.Cldr.EnCX

        Evergreen.V25.Cldr.EnCY ->
            Evergreen.V31.Cldr.EnCY

        Evergreen.V25.Cldr.EnDE ->
            Evergreen.V31.Cldr.EnDE

        Evergreen.V25.Cldr.EnDG ->
            Evergreen.V31.Cldr.EnDG

        Evergreen.V25.Cldr.EnDK ->
            Evergreen.V31.Cldr.EnDK

        Evergreen.V25.Cldr.EnDM ->
            Evergreen.V31.Cldr.EnDM

        Evergreen.V25.Cldr.EnER ->
            Evergreen.V31.Cldr.EnER

        Evergreen.V25.Cldr.EnFI ->
            Evergreen.V31.Cldr.EnFI

        Evergreen.V25.Cldr.EnFJ ->
            Evergreen.V31.Cldr.EnFJ

        Evergreen.V25.Cldr.EnFK ->
            Evergreen.V31.Cldr.EnFK

        Evergreen.V25.Cldr.EnFM ->
            Evergreen.V31.Cldr.EnFM

        Evergreen.V25.Cldr.EnGB ->
            Evergreen.V31.Cldr.EnGB

        Evergreen.V25.Cldr.EnGD ->
            Evergreen.V31.Cldr.EnGD

        Evergreen.V25.Cldr.EnGG ->
            Evergreen.V31.Cldr.EnGG

        Evergreen.V25.Cldr.EnGH ->
            Evergreen.V31.Cldr.EnGH

        Evergreen.V25.Cldr.EnGI ->
            Evergreen.V31.Cldr.EnGI

        Evergreen.V25.Cldr.EnGM ->
            Evergreen.V31.Cldr.EnGM

        Evergreen.V25.Cldr.EnGU ->
            Evergreen.V31.Cldr.EnGU

        Evergreen.V25.Cldr.EnGY ->
            Evergreen.V31.Cldr.EnGY

        Evergreen.V25.Cldr.EnHK ->
            Evergreen.V31.Cldr.EnHK

        Evergreen.V25.Cldr.EnIE ->
            Evergreen.V31.Cldr.EnIE

        Evergreen.V25.Cldr.EnIL ->
            Evergreen.V31.Cldr.EnIL

        Evergreen.V25.Cldr.EnIM ->
            Evergreen.V31.Cldr.EnIM

        Evergreen.V25.Cldr.EnIN ->
            Evergreen.V31.Cldr.EnIN

        Evergreen.V25.Cldr.EnIO ->
            Evergreen.V31.Cldr.EnIO

        Evergreen.V25.Cldr.EnJE ->
            Evergreen.V31.Cldr.EnJE

        Evergreen.V25.Cldr.EnJM ->
            Evergreen.V31.Cldr.EnJM

        Evergreen.V25.Cldr.EnKE ->
            Evergreen.V31.Cldr.EnKE

        Evergreen.V25.Cldr.EnKI ->
            Evergreen.V31.Cldr.EnKI

        Evergreen.V25.Cldr.EnKN ->
            Evergreen.V31.Cldr.EnKN

        Evergreen.V25.Cldr.EnKY ->
            Evergreen.V31.Cldr.EnKY

        Evergreen.V25.Cldr.EnLC ->
            Evergreen.V31.Cldr.EnLC

        Evergreen.V25.Cldr.EnLR ->
            Evergreen.V31.Cldr.EnLR

        Evergreen.V25.Cldr.EnLS ->
            Evergreen.V31.Cldr.EnLS

        Evergreen.V25.Cldr.EnMG ->
            Evergreen.V31.Cldr.EnMG

        Evergreen.V25.Cldr.EnMH ->
            Evergreen.V31.Cldr.EnMH

        Evergreen.V25.Cldr.EnMO ->
            Evergreen.V31.Cldr.EnMO

        Evergreen.V25.Cldr.EnMP ->
            Evergreen.V31.Cldr.EnMP

        Evergreen.V25.Cldr.EnMS ->
            Evergreen.V31.Cldr.EnMS

        Evergreen.V25.Cldr.EnMT ->
            Evergreen.V31.Cldr.EnMT

        Evergreen.V25.Cldr.EnMU ->
            Evergreen.V31.Cldr.EnMU

        Evergreen.V25.Cldr.EnMV ->
            Evergreen.V31.Cldr.EnMV

        Evergreen.V25.Cldr.EnMW ->
            Evergreen.V31.Cldr.EnMW

        Evergreen.V25.Cldr.EnMY ->
            Evergreen.V31.Cldr.EnMY

        Evergreen.V25.Cldr.EnNA ->
            Evergreen.V31.Cldr.EnNA

        Evergreen.V25.Cldr.EnNF ->
            Evergreen.V31.Cldr.EnNF

        Evergreen.V25.Cldr.EnNG ->
            Evergreen.V31.Cldr.EnNG

        Evergreen.V25.Cldr.EnNL ->
            Evergreen.V31.Cldr.EnNL

        Evergreen.V25.Cldr.EnNR ->
            Evergreen.V31.Cldr.EnNR

        Evergreen.V25.Cldr.EnNU ->
            Evergreen.V31.Cldr.EnNU

        Evergreen.V25.Cldr.EnNZ ->
            Evergreen.V31.Cldr.EnNZ

        Evergreen.V25.Cldr.EnPG ->
            Evergreen.V31.Cldr.EnPG

        Evergreen.V25.Cldr.EnPH ->
            Evergreen.V31.Cldr.EnPH

        Evergreen.V25.Cldr.EnPK ->
            Evergreen.V31.Cldr.EnPK

        Evergreen.V25.Cldr.EnPN ->
            Evergreen.V31.Cldr.EnPN

        Evergreen.V25.Cldr.EnPR ->
            Evergreen.V31.Cldr.EnPR

        Evergreen.V25.Cldr.EnPW ->
            Evergreen.V31.Cldr.EnPW

        Evergreen.V25.Cldr.EnRW ->
            Evergreen.V31.Cldr.EnRW

        Evergreen.V25.Cldr.EnSB ->
            Evergreen.V31.Cldr.EnSB

        Evergreen.V25.Cldr.EnSC ->
            Evergreen.V31.Cldr.EnSC

        Evergreen.V25.Cldr.EnSD ->
            Evergreen.V31.Cldr.EnSD

        Evergreen.V25.Cldr.EnSE ->
            Evergreen.V31.Cldr.EnSE

        Evergreen.V25.Cldr.EnSG ->
            Evergreen.V31.Cldr.EnSG

        Evergreen.V25.Cldr.EnSH ->
            Evergreen.V31.Cldr.EnSH

        Evergreen.V25.Cldr.EnSI ->
            Evergreen.V31.Cldr.EnSI

        Evergreen.V25.Cldr.EnSL ->
            Evergreen.V31.Cldr.EnSL

        Evergreen.V25.Cldr.EnSS ->
            Evergreen.V31.Cldr.EnSS

        Evergreen.V25.Cldr.EnSX ->
            Evergreen.V31.Cldr.EnSX

        Evergreen.V25.Cldr.EnSZ ->
            Evergreen.V31.Cldr.EnSZ

        Evergreen.V25.Cldr.EnTC ->
            Evergreen.V31.Cldr.EnTC

        Evergreen.V25.Cldr.EnTK ->
            Evergreen.V31.Cldr.EnTK

        Evergreen.V25.Cldr.EnTO ->
            Evergreen.V31.Cldr.EnTO

        Evergreen.V25.Cldr.EnTT ->
            Evergreen.V31.Cldr.EnTT

        Evergreen.V25.Cldr.EnTV ->
            Evergreen.V31.Cldr.EnTV

        Evergreen.V25.Cldr.EnTZ ->
            Evergreen.V31.Cldr.EnTZ

        Evergreen.V25.Cldr.EnUG ->
            Evergreen.V31.Cldr.EnUG

        Evergreen.V25.Cldr.EnUM ->
            Evergreen.V31.Cldr.EnUM

        Evergreen.V25.Cldr.EnVC ->
            Evergreen.V31.Cldr.EnVC

        Evergreen.V25.Cldr.EnVG ->
            Evergreen.V31.Cldr.EnVG

        Evergreen.V25.Cldr.EnVI ->
            Evergreen.V31.Cldr.EnVI

        Evergreen.V25.Cldr.EnVU ->
            Evergreen.V31.Cldr.EnVU

        Evergreen.V25.Cldr.EnWS ->
            Evergreen.V31.Cldr.EnWS

        Evergreen.V25.Cldr.EnZA ->
            Evergreen.V31.Cldr.EnZA

        Evergreen.V25.Cldr.EnZM ->
            Evergreen.V31.Cldr.EnZM

        Evergreen.V25.Cldr.EnZW ->
            Evergreen.V31.Cldr.EnZW

        Evergreen.V25.Cldr.Es ->
            Evergreen.V31.Cldr.Es

        Evergreen.V25.Cldr.Es419 ->
            Evergreen.V31.Cldr.Es419

        Evergreen.V25.Cldr.EsAR ->
            Evergreen.V31.Cldr.EsAR

        Evergreen.V25.Cldr.EsBO ->
            Evergreen.V31.Cldr.EsBO

        Evergreen.V25.Cldr.EsBR ->
            Evergreen.V31.Cldr.EsBR

        Evergreen.V25.Cldr.EsBZ ->
            Evergreen.V31.Cldr.EsBZ

        Evergreen.V25.Cldr.EsCL ->
            Evergreen.V31.Cldr.EsCL

        Evergreen.V25.Cldr.EsCO ->
            Evergreen.V31.Cldr.EsCO

        Evergreen.V25.Cldr.EsCR ->
            Evergreen.V31.Cldr.EsCR

        Evergreen.V25.Cldr.EsCU ->
            Evergreen.V31.Cldr.EsCU

        Evergreen.V25.Cldr.EsDO ->
            Evergreen.V31.Cldr.EsDO

        Evergreen.V25.Cldr.EsEA ->
            Evergreen.V31.Cldr.EsEA

        Evergreen.V25.Cldr.EsEC ->
            Evergreen.V31.Cldr.EsEC

        Evergreen.V25.Cldr.EsGQ ->
            Evergreen.V31.Cldr.EsGQ

        Evergreen.V25.Cldr.EsGT ->
            Evergreen.V31.Cldr.EsGT

        Evergreen.V25.Cldr.EsHN ->
            Evergreen.V31.Cldr.EsHN

        Evergreen.V25.Cldr.EsIC ->
            Evergreen.V31.Cldr.EsIC

        Evergreen.V25.Cldr.EsMX ->
            Evergreen.V31.Cldr.EsMX

        Evergreen.V25.Cldr.EsNI ->
            Evergreen.V31.Cldr.EsNI

        Evergreen.V25.Cldr.EsPA ->
            Evergreen.V31.Cldr.EsPA

        Evergreen.V25.Cldr.EsPE ->
            Evergreen.V31.Cldr.EsPE

        Evergreen.V25.Cldr.EsPH ->
            Evergreen.V31.Cldr.EsPH

        Evergreen.V25.Cldr.EsPR ->
            Evergreen.V31.Cldr.EsPR

        Evergreen.V25.Cldr.EsPY ->
            Evergreen.V31.Cldr.EsPY

        Evergreen.V25.Cldr.EsSV ->
            Evergreen.V31.Cldr.EsSV

        Evergreen.V25.Cldr.EsUS ->
            Evergreen.V31.Cldr.EsUS

        Evergreen.V25.Cldr.EsUY ->
            Evergreen.V31.Cldr.EsUY

        Evergreen.V25.Cldr.EsVE ->
            Evergreen.V31.Cldr.EsVE

        Evergreen.V25.Cldr.Et ->
            Evergreen.V31.Cldr.Et

        Evergreen.V25.Cldr.Eu ->
            Evergreen.V31.Cldr.Eu

        Evergreen.V25.Cldr.Fa ->
            Evergreen.V31.Cldr.Fa

        Evergreen.V25.Cldr.FaAF ->
            Evergreen.V31.Cldr.FaAF

        Evergreen.V25.Cldr.Fi ->
            Evergreen.V31.Cldr.Fi

        Evergreen.V25.Cldr.Fil ->
            Evergreen.V31.Cldr.Fil

        Evergreen.V25.Cldr.Fr ->
            Evergreen.V31.Cldr.Fr

        Evergreen.V25.Cldr.FrBE ->
            Evergreen.V31.Cldr.FrBE

        Evergreen.V25.Cldr.FrBF ->
            Evergreen.V31.Cldr.FrBF

        Evergreen.V25.Cldr.FrBI ->
            Evergreen.V31.Cldr.FrBI

        Evergreen.V25.Cldr.FrBJ ->
            Evergreen.V31.Cldr.FrBJ

        Evergreen.V25.Cldr.FrBL ->
            Evergreen.V31.Cldr.FrBL

        Evergreen.V25.Cldr.FrCA ->
            Evergreen.V31.Cldr.FrCA

        Evergreen.V25.Cldr.FrCD ->
            Evergreen.V31.Cldr.FrCD

        Evergreen.V25.Cldr.FrCF ->
            Evergreen.V31.Cldr.FrCF

        Evergreen.V25.Cldr.FrCG ->
            Evergreen.V31.Cldr.FrCG

        Evergreen.V25.Cldr.FrCH ->
            Evergreen.V31.Cldr.FrCH

        Evergreen.V25.Cldr.FrCI ->
            Evergreen.V31.Cldr.FrCI

        Evergreen.V25.Cldr.FrCM ->
            Evergreen.V31.Cldr.FrCM

        Evergreen.V25.Cldr.FrDJ ->
            Evergreen.V31.Cldr.FrDJ

        Evergreen.V25.Cldr.FrDZ ->
            Evergreen.V31.Cldr.FrDZ

        Evergreen.V25.Cldr.FrGA ->
            Evergreen.V31.Cldr.FrGA

        Evergreen.V25.Cldr.FrGF ->
            Evergreen.V31.Cldr.FrGF

        Evergreen.V25.Cldr.FrGN ->
            Evergreen.V31.Cldr.FrGN

        Evergreen.V25.Cldr.FrGP ->
            Evergreen.V31.Cldr.FrGP

        Evergreen.V25.Cldr.FrGQ ->
            Evergreen.V31.Cldr.FrGQ

        Evergreen.V25.Cldr.FrHT ->
            Evergreen.V31.Cldr.FrHT

        Evergreen.V25.Cldr.FrKM ->
            Evergreen.V31.Cldr.FrKM

        Evergreen.V25.Cldr.FrLU ->
            Evergreen.V31.Cldr.FrLU

        Evergreen.V25.Cldr.FrMA ->
            Evergreen.V31.Cldr.FrMA

        Evergreen.V25.Cldr.FrMC ->
            Evergreen.V31.Cldr.FrMC

        Evergreen.V25.Cldr.FrMF ->
            Evergreen.V31.Cldr.FrMF

        Evergreen.V25.Cldr.FrMG ->
            Evergreen.V31.Cldr.FrMG

        Evergreen.V25.Cldr.FrML ->
            Evergreen.V31.Cldr.FrML

        Evergreen.V25.Cldr.FrMQ ->
            Evergreen.V31.Cldr.FrMQ

        Evergreen.V25.Cldr.FrMR ->
            Evergreen.V31.Cldr.FrMR

        Evergreen.V25.Cldr.FrMU ->
            Evergreen.V31.Cldr.FrMU

        Evergreen.V25.Cldr.FrNC ->
            Evergreen.V31.Cldr.FrNC

        Evergreen.V25.Cldr.FrNE ->
            Evergreen.V31.Cldr.FrNE

        Evergreen.V25.Cldr.FrPF ->
            Evergreen.V31.Cldr.FrPF

        Evergreen.V25.Cldr.FrPM ->
            Evergreen.V31.Cldr.FrPM

        Evergreen.V25.Cldr.FrRE ->
            Evergreen.V31.Cldr.FrRE

        Evergreen.V25.Cldr.FrRW ->
            Evergreen.V31.Cldr.FrRW

        Evergreen.V25.Cldr.FrSC ->
            Evergreen.V31.Cldr.FrSC

        Evergreen.V25.Cldr.FrSN ->
            Evergreen.V31.Cldr.FrSN

        Evergreen.V25.Cldr.FrSY ->
            Evergreen.V31.Cldr.FrSY

        Evergreen.V25.Cldr.FrTD ->
            Evergreen.V31.Cldr.FrTD

        Evergreen.V25.Cldr.FrTG ->
            Evergreen.V31.Cldr.FrTG

        Evergreen.V25.Cldr.FrTN ->
            Evergreen.V31.Cldr.FrTN

        Evergreen.V25.Cldr.FrVU ->
            Evergreen.V31.Cldr.FrVU

        Evergreen.V25.Cldr.FrWF ->
            Evergreen.V31.Cldr.FrWF

        Evergreen.V25.Cldr.FrYT ->
            Evergreen.V31.Cldr.FrYT

        Evergreen.V25.Cldr.Ga ->
            Evergreen.V31.Cldr.Ga

        Evergreen.V25.Cldr.GaGB ->
            Evergreen.V31.Cldr.GaGB

        Evergreen.V25.Cldr.Gd ->
            Evergreen.V31.Cldr.Gd

        Evergreen.V25.Cldr.Gl ->
            Evergreen.V31.Cldr.Gl

        Evergreen.V25.Cldr.Gu ->
            Evergreen.V31.Cldr.Gu

        Evergreen.V25.Cldr.Ha ->
            Evergreen.V31.Cldr.Ha

        Evergreen.V25.Cldr.HaGH ->
            Evergreen.V31.Cldr.HaGH

        Evergreen.V25.Cldr.HaNE ->
            Evergreen.V31.Cldr.HaNE

        Evergreen.V25.Cldr.He ->
            Evergreen.V31.Cldr.He

        Evergreen.V25.Cldr.Hi ->
            Evergreen.V31.Cldr.Hi

        Evergreen.V25.Cldr.HiLatn ->
            Evergreen.V31.Cldr.HiLatn

        Evergreen.V25.Cldr.Hr ->
            Evergreen.V31.Cldr.Hr

        Evergreen.V25.Cldr.HrBA ->
            Evergreen.V31.Cldr.HrBA

        Evergreen.V25.Cldr.Hu ->
            Evergreen.V31.Cldr.Hu

        Evergreen.V25.Cldr.Hy ->
            Evergreen.V31.Cldr.Hy

        Evergreen.V25.Cldr.Id ->
            Evergreen.V31.Cldr.Id

        Evergreen.V25.Cldr.Ig ->
            Evergreen.V31.Cldr.Ig

        Evergreen.V25.Cldr.Is ->
            Evergreen.V31.Cldr.Is

        Evergreen.V25.Cldr.It ->
            Evergreen.V31.Cldr.It

        Evergreen.V25.Cldr.ItCH ->
            Evergreen.V31.Cldr.ItCH

        Evergreen.V25.Cldr.ItSM ->
            Evergreen.V31.Cldr.ItSM

        Evergreen.V25.Cldr.ItVA ->
            Evergreen.V31.Cldr.ItVA

        Evergreen.V25.Cldr.Ja ->
            Evergreen.V31.Cldr.Ja

        Evergreen.V25.Cldr.Jv ->
            Evergreen.V31.Cldr.Jv

        Evergreen.V25.Cldr.Ka ->
            Evergreen.V31.Cldr.Ka

        Evergreen.V25.Cldr.Kk ->
            Evergreen.V31.Cldr.Kk

        Evergreen.V25.Cldr.Km ->
            Evergreen.V31.Cldr.Km

        Evergreen.V25.Cldr.Kn ->
            Evergreen.V31.Cldr.Kn

        Evergreen.V25.Cldr.Ko ->
            Evergreen.V31.Cldr.Ko

        Evergreen.V25.Cldr.KoKP ->
            Evergreen.V31.Cldr.KoKP

        Evergreen.V25.Cldr.Kok ->
            Evergreen.V31.Cldr.Kok

        Evergreen.V25.Cldr.Ky ->
            Evergreen.V31.Cldr.Ky

        Evergreen.V25.Cldr.Lo ->
            Evergreen.V31.Cldr.Lo

        Evergreen.V25.Cldr.Lt ->
            Evergreen.V31.Cldr.Lt

        Evergreen.V25.Cldr.Lv ->
            Evergreen.V31.Cldr.Lv

        Evergreen.V25.Cldr.Mk ->
            Evergreen.V31.Cldr.Mk

        Evergreen.V25.Cldr.Ml ->
            Evergreen.V31.Cldr.Ml

        Evergreen.V25.Cldr.Mn ->
            Evergreen.V31.Cldr.Mn

        Evergreen.V25.Cldr.Mr ->
            Evergreen.V31.Cldr.Mr

        Evergreen.V25.Cldr.Ms ->
            Evergreen.V31.Cldr.Ms

        Evergreen.V25.Cldr.MsBN ->
            Evergreen.V31.Cldr.MsBN

        Evergreen.V25.Cldr.MsID ->
            Evergreen.V31.Cldr.MsID

        Evergreen.V25.Cldr.MsSG ->
            Evergreen.V31.Cldr.MsSG

        Evergreen.V25.Cldr.My ->
            Evergreen.V31.Cldr.My

        Evergreen.V25.Cldr.Nb ->
            Evergreen.V31.Cldr.Nb

        Evergreen.V25.Cldr.NbSJ ->
            Evergreen.V31.Cldr.NbSJ

        Evergreen.V25.Cldr.Ne ->
            Evergreen.V31.Cldr.Ne

        Evergreen.V25.Cldr.NeIN ->
            Evergreen.V31.Cldr.NeIN

        Evergreen.V25.Cldr.Nl ->
            Evergreen.V31.Cldr.Nl

        Evergreen.V25.Cldr.NlAW ->
            Evergreen.V31.Cldr.NlAW

        Evergreen.V25.Cldr.NlBE ->
            Evergreen.V31.Cldr.NlBE

        Evergreen.V25.Cldr.NlBQ ->
            Evergreen.V31.Cldr.NlBQ

        Evergreen.V25.Cldr.NlCW ->
            Evergreen.V31.Cldr.NlCW

        Evergreen.V25.Cldr.NlSR ->
            Evergreen.V31.Cldr.NlSR

        Evergreen.V25.Cldr.NlSX ->
            Evergreen.V31.Cldr.NlSX

        Evergreen.V25.Cldr.Nn ->
            Evergreen.V31.Cldr.Nn

        Evergreen.V25.Cldr.No ->
            Evergreen.V31.Cldr.No

        Evergreen.V25.Cldr.Or ->
            Evergreen.V31.Cldr.Or

        Evergreen.V25.Cldr.Pa ->
            Evergreen.V31.Cldr.Pa

        Evergreen.V25.Cldr.PaGuru ->
            Evergreen.V31.Cldr.PaGuru

        Evergreen.V25.Cldr.Pcm ->
            Evergreen.V31.Cldr.Pcm

        Evergreen.V25.Cldr.Pl ->
            Evergreen.V31.Cldr.Pl

        Evergreen.V25.Cldr.Ps ->
            Evergreen.V31.Cldr.Ps

        Evergreen.V25.Cldr.PsPK ->
            Evergreen.V31.Cldr.PsPK

        Evergreen.V25.Cldr.Pt ->
            Evergreen.V31.Cldr.Pt

        Evergreen.V25.Cldr.PtAO ->
            Evergreen.V31.Cldr.PtAO

        Evergreen.V25.Cldr.PtCH ->
            Evergreen.V31.Cldr.PtCH

        Evergreen.V25.Cldr.PtCV ->
            Evergreen.V31.Cldr.PtCV

        Evergreen.V25.Cldr.PtGQ ->
            Evergreen.V31.Cldr.PtGQ

        Evergreen.V25.Cldr.PtGW ->
            Evergreen.V31.Cldr.PtGW

        Evergreen.V25.Cldr.PtLU ->
            Evergreen.V31.Cldr.PtLU

        Evergreen.V25.Cldr.PtMO ->
            Evergreen.V31.Cldr.PtMO

        Evergreen.V25.Cldr.PtMZ ->
            Evergreen.V31.Cldr.PtMZ

        Evergreen.V25.Cldr.PtPT ->
            Evergreen.V31.Cldr.PtPT

        Evergreen.V25.Cldr.PtST ->
            Evergreen.V31.Cldr.PtST

        Evergreen.V25.Cldr.PtTL ->
            Evergreen.V31.Cldr.PtTL

        Evergreen.V25.Cldr.Ro ->
            Evergreen.V31.Cldr.Ro

        Evergreen.V25.Cldr.RoMD ->
            Evergreen.V31.Cldr.RoMD

        Evergreen.V25.Cldr.Ru ->
            Evergreen.V31.Cldr.Ru

        Evergreen.V25.Cldr.RuBY ->
            Evergreen.V31.Cldr.RuBY

        Evergreen.V25.Cldr.RuKG ->
            Evergreen.V31.Cldr.RuKG

        Evergreen.V25.Cldr.RuKZ ->
            Evergreen.V31.Cldr.RuKZ

        Evergreen.V25.Cldr.RuMD ->
            Evergreen.V31.Cldr.RuMD

        Evergreen.V25.Cldr.RuUA ->
            Evergreen.V31.Cldr.RuUA

        Evergreen.V25.Cldr.Sd ->
            Evergreen.V31.Cldr.Sd

        Evergreen.V25.Cldr.SdArab ->
            Evergreen.V31.Cldr.SdArab

        Evergreen.V25.Cldr.Si ->
            Evergreen.V31.Cldr.Si

        Evergreen.V25.Cldr.Sk ->
            Evergreen.V31.Cldr.Sk

        Evergreen.V25.Cldr.Sl ->
            Evergreen.V31.Cldr.Sl

        Evergreen.V25.Cldr.So ->
            Evergreen.V31.Cldr.So

        Evergreen.V25.Cldr.SoDJ ->
            Evergreen.V31.Cldr.SoDJ

        Evergreen.V25.Cldr.SoET ->
            Evergreen.V31.Cldr.SoET

        Evergreen.V25.Cldr.SoKE ->
            Evergreen.V31.Cldr.SoKE

        Evergreen.V25.Cldr.Sq ->
            Evergreen.V31.Cldr.Sq

        Evergreen.V25.Cldr.SqMK ->
            Evergreen.V31.Cldr.SqMK

        Evergreen.V25.Cldr.SqXK ->
            Evergreen.V31.Cldr.SqXK

        Evergreen.V25.Cldr.Sr ->
            Evergreen.V31.Cldr.Sr

        Evergreen.V25.Cldr.SrCyrl ->
            Evergreen.V31.Cldr.SrCyrl

        Evergreen.V25.Cldr.SrCyrlBA ->
            Evergreen.V31.Cldr.SrCyrlBA

        Evergreen.V25.Cldr.SrCyrlME ->
            Evergreen.V31.Cldr.SrCyrlME

        Evergreen.V25.Cldr.SrCyrlXK ->
            Evergreen.V31.Cldr.SrCyrlXK

        Evergreen.V25.Cldr.SrLatn ->
            Evergreen.V31.Cldr.SrLatn

        Evergreen.V25.Cldr.SrLatnBA ->
            Evergreen.V31.Cldr.SrLatnBA

        Evergreen.V25.Cldr.SrLatnME ->
            Evergreen.V31.Cldr.SrLatnME

        Evergreen.V25.Cldr.SrLatnXK ->
            Evergreen.V31.Cldr.SrLatnXK

        Evergreen.V25.Cldr.Sv ->
            Evergreen.V31.Cldr.Sv

        Evergreen.V25.Cldr.SvAX ->
            Evergreen.V31.Cldr.SvAX

        Evergreen.V25.Cldr.SvFI ->
            Evergreen.V31.Cldr.SvFI

        Evergreen.V25.Cldr.Sw ->
            Evergreen.V31.Cldr.Sw

        Evergreen.V25.Cldr.SwCD ->
            Evergreen.V31.Cldr.SwCD

        Evergreen.V25.Cldr.SwKE ->
            Evergreen.V31.Cldr.SwKE

        Evergreen.V25.Cldr.SwUG ->
            Evergreen.V31.Cldr.SwUG

        Evergreen.V25.Cldr.Ta ->
            Evergreen.V31.Cldr.Ta

        Evergreen.V25.Cldr.TaLK ->
            Evergreen.V31.Cldr.TaLK

        Evergreen.V25.Cldr.TaMY ->
            Evergreen.V31.Cldr.TaMY

        Evergreen.V25.Cldr.TaSG ->
            Evergreen.V31.Cldr.TaSG

        Evergreen.V25.Cldr.Te ->
            Evergreen.V31.Cldr.Te

        Evergreen.V25.Cldr.Th ->
            Evergreen.V31.Cldr.Th

        Evergreen.V25.Cldr.Tk ->
            Evergreen.V31.Cldr.Tk

        Evergreen.V25.Cldr.Tr ->
            Evergreen.V31.Cldr.Tr

        Evergreen.V25.Cldr.TrCY ->
            Evergreen.V31.Cldr.TrCY

        Evergreen.V25.Cldr.Uk ->
            Evergreen.V31.Cldr.Uk

        Evergreen.V25.Cldr.Ur ->
            Evergreen.V31.Cldr.Ur

        Evergreen.V25.Cldr.UrIN ->
            Evergreen.V31.Cldr.UrIN

        Evergreen.V25.Cldr.Uz ->
            Evergreen.V31.Cldr.Uz

        Evergreen.V25.Cldr.UzLatn ->
            Evergreen.V31.Cldr.UzLatn

        Evergreen.V25.Cldr.Vi ->
            Evergreen.V31.Cldr.Vi

        Evergreen.V25.Cldr.Yo ->
            Evergreen.V31.Cldr.Yo

        Evergreen.V25.Cldr.YoBJ ->
            Evergreen.V31.Cldr.YoBJ

        Evergreen.V25.Cldr.Yue ->
            Evergreen.V31.Cldr.Yue

        Evergreen.V25.Cldr.YueHans ->
            Evergreen.V31.Cldr.YueHans

        Evergreen.V25.Cldr.YueHant ->
            Evergreen.V31.Cldr.YueHant

        Evergreen.V25.Cldr.Zh ->
            Evergreen.V31.Cldr.Zh

        Evergreen.V25.Cldr.ZhHans ->
            Evergreen.V31.Cldr.ZhHans

        Evergreen.V25.Cldr.ZhHansHK ->
            Evergreen.V31.Cldr.ZhHansHK

        Evergreen.V25.Cldr.ZhHansMO ->
            Evergreen.V31.Cldr.ZhHansMO

        Evergreen.V25.Cldr.ZhHansSG ->
            Evergreen.V31.Cldr.ZhHansSG

        Evergreen.V25.Cldr.ZhHant ->
            Evergreen.V31.Cldr.ZhHant

        Evergreen.V25.Cldr.ZhHantHK ->
            Evergreen.V31.Cldr.ZhHantHK

        Evergreen.V25.Cldr.ZhHantMO ->
            Evergreen.V31.Cldr.ZhHantMO

        Evergreen.V25.Cldr.Zu ->
            Evergreen.V31.Cldr.Zu


migrate_Types_Country : Evergreen.V25.Types.Country -> Evergreen.V31.Types.Country
migrate_Types_Country old =
    case old of
        Evergreen.V25.Types.Iso3166 p0 ->
            Evergreen.V31.Types.Iso3166 (p0 |> migrate_Cldr_CountryCode)

        Evergreen.V25.Types.PartiallyRecognized p0 ->
            Evergreen.V31.Types.PartiallyRecognized p0


migrate_Types_Difficulty : Evergreen.V25.Types.Difficulty -> Evergreen.V31.Types.Difficulty
migrate_Types_Difficulty old =
    case old of
        Evergreen.V25.Types.Easy ->
            Evergreen.V31.Types.Easy

        Evergreen.V25.Types.Normal ->
            Evergreen.V31.Types.Normal

        Evergreen.V25.Types.Hard ->
            Evergreen.V31.Types.Hard


migrate_Types_FrontendMsg : Evergreen.V25.Types.FrontendMsg -> Evergreen.V31.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V25.Types.UrlClicked p0 ->
            Evergreen.V31.Types.UrlClicked p0

        Evergreen.V25.Types.UrlChanged p0 ->
            Evergreen.V31.Types.UrlChanged p0

        Evergreen.V25.Types.Play ->
            Evergreen.V31.Types.Play

        Evergreen.V25.Types.Seed p0 ->
            Evergreen.V31.Types.Seed p0

        Evergreen.V25.Types.Pick p0 ->
            Evergreen.V31.Types.Pick (p0 |> migrate_Types_Country)

        Evergreen.V25.Types.Next ->
            Evergreen.V31.Types.Next

        Evergreen.V25.Types.ChangeOptions p0 ->
            Evergreen.V31.Types.ChangeOptions (p0 |> migrate_Types_GameOptions)

        Evergreen.V25.Types.Locale p0 ->
            Evergreen.V31.Types.Locale (p0 |> migrate_Cldr_Locale)

        Evergreen.V25.Types.ChangingLocale p0 ->
            Evergreen.V31.Types.ChangingLocale p0

        Evergreen.V25.Types.Move p0 p1 ->
            Evergreen.V31.Types.Move (p0 |> migrate_Types_Country) p1

        Evergreen.V25.Types.SelectForMove p0 ->
            Evergreen.V31.Types.SelectForMove (p0 |> migrate_Types_Country)


migrate_Types_GameOptions : Evergreen.V25.Types.GameOptions -> Evergreen.V31.Types.GameOptions
migrate_Types_GameOptions old =
    { gameLength = old.gameLength
    , difficulty = old.difficulty |> migrate_Types_Difficulty
    , answersPerCard = old.answersPerCard
    , guessPatterns = old.guessPatterns |> List.map (Tuple.mapBoth migrate_Types_Property migrate_Types_Property)
    , sovereignOnly = old.sovereignOnly
    }


migrate_Types_Property : Evergreen.V25.Types.Property -> Evergreen.V31.Types.Property
migrate_Types_Property old =
    case old of
        Evergreen.V25.Types.Flag ->
            Evergreen.V31.Types.Flag

        Evergreen.V25.Types.Name ->
            Evergreen.V31.Types.Name
