module Evergreen.Migrate.V42 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V37.Cldr
import Evergreen.V37.Main
import Evergreen.V37.Main.Pages.Model
import Evergreen.V37.Main.Pages.Msg
import Evergreen.V37.Pages.Finished
import Evergreen.V37.Pages.Home_
import Evergreen.V37.Pages.NotFound_
import Evergreen.V37.Pages.Play
import Evergreen.V37.Pages.Sort
import Evergreen.V37.Shared
import Evergreen.V37.Shared.Model
import Evergreen.V37.Shared.Msg
import Evergreen.V37.Types
import Evergreen.V42.Cldr
import Evergreen.V42.Main
import Evergreen.V42.Main.Pages.Model
import Evergreen.V42.Main.Pages.Msg
import Evergreen.V42.Pages.Finished
import Evergreen.V42.Pages.Home_
import Evergreen.V42.Pages.NotFound_
import Evergreen.V42.Pages.Play
import Evergreen.V42.Pages.Sort
import Evergreen.V42.Shared
import Evergreen.V42.Shared.Model
import Evergreen.V42.Shared.Msg
import Evergreen.V42.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V37.Types.FrontendModel -> ModelMigration Evergreen.V42.Types.FrontendModel Evergreen.V42.Types.FrontendMsg
frontendModel _ =
    ModelUnchanged


backendModel : Evergreen.V37.Types.BackendModel -> ModelMigration Evergreen.V42.Types.BackendModel Evergreen.V42.Types.BackendMsg
backendModel _ =
    ModelUnchanged


frontendMsg : Evergreen.V37.Types.FrontendMsg -> MsgMigration Evergreen.V42.Types.FrontendMsg Evergreen.V42.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V37.Types.ToBackend -> MsgMigration Evergreen.V42.Types.ToBackend Evergreen.V42.Types.BackendMsg
toBackend _ =
    MsgUnchanged


backendMsg : Evergreen.V37.Types.BackendMsg -> MsgMigration Evergreen.V42.Types.BackendMsg Evergreen.V42.Types.BackendMsg
backendMsg _ =
    MsgUnchanged


toFrontend : Evergreen.V37.Types.ToFrontend -> MsgMigration Evergreen.V42.Types.ToFrontend Evergreen.V42.Types.FrontendMsg
toFrontend _ =
    MsgUnchanged


migrate_Types_FrontendMsg : Evergreen.V37.Types.FrontendMsg -> Evergreen.V42.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    old |> migrate_Main_Msg


migrate_Cldr_CountryCode : Evergreen.V37.Cldr.CountryCode -> Evergreen.V42.Cldr.CountryCode
migrate_Cldr_CountryCode old =
    case old of
        Evergreen.V37.Cldr.AD ->
            Evergreen.V42.Cldr.AD

        Evergreen.V37.Cldr.AE ->
            Evergreen.V42.Cldr.AE

        Evergreen.V37.Cldr.AF ->
            Evergreen.V42.Cldr.AF

        Evergreen.V37.Cldr.AG ->
            Evergreen.V42.Cldr.AG

        Evergreen.V37.Cldr.AI ->
            Evergreen.V42.Cldr.AI

        Evergreen.V37.Cldr.AL ->
            Evergreen.V42.Cldr.AL

        Evergreen.V37.Cldr.AM ->
            Evergreen.V42.Cldr.AM

        Evergreen.V37.Cldr.AO ->
            Evergreen.V42.Cldr.AO

        Evergreen.V37.Cldr.AQ ->
            Evergreen.V42.Cldr.AQ

        Evergreen.V37.Cldr.AR ->
            Evergreen.V42.Cldr.AR

        Evergreen.V37.Cldr.AS ->
            Evergreen.V42.Cldr.AS

        Evergreen.V37.Cldr.AT ->
            Evergreen.V42.Cldr.AT

        Evergreen.V37.Cldr.AU ->
            Evergreen.V42.Cldr.AU

        Evergreen.V37.Cldr.AW ->
            Evergreen.V42.Cldr.AW

        Evergreen.V37.Cldr.AX ->
            Evergreen.V42.Cldr.AX

        Evergreen.V37.Cldr.AZ ->
            Evergreen.V42.Cldr.AZ

        Evergreen.V37.Cldr.BA ->
            Evergreen.V42.Cldr.BA

        Evergreen.V37.Cldr.BB ->
            Evergreen.V42.Cldr.BB

        Evergreen.V37.Cldr.BD ->
            Evergreen.V42.Cldr.BD

        Evergreen.V37.Cldr.BE ->
            Evergreen.V42.Cldr.BE

        Evergreen.V37.Cldr.BF ->
            Evergreen.V42.Cldr.BF

        Evergreen.V37.Cldr.BG ->
            Evergreen.V42.Cldr.BG

        Evergreen.V37.Cldr.BH ->
            Evergreen.V42.Cldr.BH

        Evergreen.V37.Cldr.BI ->
            Evergreen.V42.Cldr.BI

        Evergreen.V37.Cldr.BJ ->
            Evergreen.V42.Cldr.BJ

        Evergreen.V37.Cldr.BL ->
            Evergreen.V42.Cldr.BL

        Evergreen.V37.Cldr.BM ->
            Evergreen.V42.Cldr.BM

        Evergreen.V37.Cldr.BN ->
            Evergreen.V42.Cldr.BN

        Evergreen.V37.Cldr.BO ->
            Evergreen.V42.Cldr.BO

        Evergreen.V37.Cldr.BQ ->
            Evergreen.V42.Cldr.BQ

        Evergreen.V37.Cldr.BR ->
            Evergreen.V42.Cldr.BR

        Evergreen.V37.Cldr.BS ->
            Evergreen.V42.Cldr.BS

        Evergreen.V37.Cldr.BT ->
            Evergreen.V42.Cldr.BT

        Evergreen.V37.Cldr.BV ->
            Evergreen.V42.Cldr.BV

        Evergreen.V37.Cldr.BW ->
            Evergreen.V42.Cldr.BW

        Evergreen.V37.Cldr.BY ->
            Evergreen.V42.Cldr.BY

        Evergreen.V37.Cldr.BZ ->
            Evergreen.V42.Cldr.BZ

        Evergreen.V37.Cldr.CA ->
            Evergreen.V42.Cldr.CA

        Evergreen.V37.Cldr.CC ->
            Evergreen.V42.Cldr.CC

        Evergreen.V37.Cldr.CD ->
            Evergreen.V42.Cldr.CD

        Evergreen.V37.Cldr.CF ->
            Evergreen.V42.Cldr.CF

        Evergreen.V37.Cldr.CG ->
            Evergreen.V42.Cldr.CG

        Evergreen.V37.Cldr.CH ->
            Evergreen.V42.Cldr.CH

        Evergreen.V37.Cldr.CI ->
            Evergreen.V42.Cldr.CI

        Evergreen.V37.Cldr.CK ->
            Evergreen.V42.Cldr.CK

        Evergreen.V37.Cldr.CL ->
            Evergreen.V42.Cldr.CL

        Evergreen.V37.Cldr.CM ->
            Evergreen.V42.Cldr.CM

        Evergreen.V37.Cldr.CN ->
            Evergreen.V42.Cldr.CN

        Evergreen.V37.Cldr.CO ->
            Evergreen.V42.Cldr.CO

        Evergreen.V37.Cldr.CR ->
            Evergreen.V42.Cldr.CR

        Evergreen.V37.Cldr.CU ->
            Evergreen.V42.Cldr.CU

        Evergreen.V37.Cldr.CV ->
            Evergreen.V42.Cldr.CV

        Evergreen.V37.Cldr.CW ->
            Evergreen.V42.Cldr.CW

        Evergreen.V37.Cldr.CX ->
            Evergreen.V42.Cldr.CX

        Evergreen.V37.Cldr.CY ->
            Evergreen.V42.Cldr.CY

        Evergreen.V37.Cldr.CZ ->
            Evergreen.V42.Cldr.CZ

        Evergreen.V37.Cldr.DE ->
            Evergreen.V42.Cldr.DE

        Evergreen.V37.Cldr.DJ ->
            Evergreen.V42.Cldr.DJ

        Evergreen.V37.Cldr.DK ->
            Evergreen.V42.Cldr.DK

        Evergreen.V37.Cldr.DM ->
            Evergreen.V42.Cldr.DM

        Evergreen.V37.Cldr.DO ->
            Evergreen.V42.Cldr.DO

        Evergreen.V37.Cldr.DZ ->
            Evergreen.V42.Cldr.DZ

        Evergreen.V37.Cldr.EC ->
            Evergreen.V42.Cldr.EC

        Evergreen.V37.Cldr.EE ->
            Evergreen.V42.Cldr.EE

        Evergreen.V37.Cldr.EG ->
            Evergreen.V42.Cldr.EG

        Evergreen.V37.Cldr.EH ->
            Evergreen.V42.Cldr.EH

        Evergreen.V37.Cldr.ER ->
            Evergreen.V42.Cldr.ER

        Evergreen.V37.Cldr.ES ->
            Evergreen.V42.Cldr.ES

        Evergreen.V37.Cldr.ET ->
            Evergreen.V42.Cldr.ET

        Evergreen.V37.Cldr.FI ->
            Evergreen.V42.Cldr.FI

        Evergreen.V37.Cldr.FJ ->
            Evergreen.V42.Cldr.FJ

        Evergreen.V37.Cldr.FK ->
            Evergreen.V42.Cldr.FK

        Evergreen.V37.Cldr.FM ->
            Evergreen.V42.Cldr.FM

        Evergreen.V37.Cldr.FO ->
            Evergreen.V42.Cldr.FO

        Evergreen.V37.Cldr.FR ->
            Evergreen.V42.Cldr.FR

        Evergreen.V37.Cldr.GA ->
            Evergreen.V42.Cldr.GA

        Evergreen.V37.Cldr.GB ->
            Evergreen.V42.Cldr.GB

        Evergreen.V37.Cldr.GD ->
            Evergreen.V42.Cldr.GD

        Evergreen.V37.Cldr.GE ->
            Evergreen.V42.Cldr.GE

        Evergreen.V37.Cldr.GF ->
            Evergreen.V42.Cldr.GF

        Evergreen.V37.Cldr.GG ->
            Evergreen.V42.Cldr.GG

        Evergreen.V37.Cldr.GH ->
            Evergreen.V42.Cldr.GH

        Evergreen.V37.Cldr.GI ->
            Evergreen.V42.Cldr.GI

        Evergreen.V37.Cldr.GL ->
            Evergreen.V42.Cldr.GL

        Evergreen.V37.Cldr.GM ->
            Evergreen.V42.Cldr.GM

        Evergreen.V37.Cldr.GN ->
            Evergreen.V42.Cldr.GN

        Evergreen.V37.Cldr.GP ->
            Evergreen.V42.Cldr.GP

        Evergreen.V37.Cldr.GQ ->
            Evergreen.V42.Cldr.GQ

        Evergreen.V37.Cldr.GR ->
            Evergreen.V42.Cldr.GR

        Evergreen.V37.Cldr.GS ->
            Evergreen.V42.Cldr.GS

        Evergreen.V37.Cldr.GT_ ->
            Evergreen.V42.Cldr.GT_

        Evergreen.V37.Cldr.GU ->
            Evergreen.V42.Cldr.GU

        Evergreen.V37.Cldr.GW ->
            Evergreen.V42.Cldr.GW

        Evergreen.V37.Cldr.GY ->
            Evergreen.V42.Cldr.GY

        Evergreen.V37.Cldr.HK ->
            Evergreen.V42.Cldr.HK

        Evergreen.V37.Cldr.HM ->
            Evergreen.V42.Cldr.HM

        Evergreen.V37.Cldr.HN ->
            Evergreen.V42.Cldr.HN

        Evergreen.V37.Cldr.HR ->
            Evergreen.V42.Cldr.HR

        Evergreen.V37.Cldr.HT ->
            Evergreen.V42.Cldr.HT

        Evergreen.V37.Cldr.HU ->
            Evergreen.V42.Cldr.HU

        Evergreen.V37.Cldr.ID ->
            Evergreen.V42.Cldr.ID

        Evergreen.V37.Cldr.IE ->
            Evergreen.V42.Cldr.IE

        Evergreen.V37.Cldr.IL ->
            Evergreen.V42.Cldr.IL

        Evergreen.V37.Cldr.IM ->
            Evergreen.V42.Cldr.IM

        Evergreen.V37.Cldr.IN ->
            Evergreen.V42.Cldr.IN

        Evergreen.V37.Cldr.IO ->
            Evergreen.V42.Cldr.IO

        Evergreen.V37.Cldr.IQ ->
            Evergreen.V42.Cldr.IQ

        Evergreen.V37.Cldr.IR ->
            Evergreen.V42.Cldr.IR

        Evergreen.V37.Cldr.IS ->
            Evergreen.V42.Cldr.IS

        Evergreen.V37.Cldr.IT ->
            Evergreen.V42.Cldr.IT

        Evergreen.V37.Cldr.JE ->
            Evergreen.V42.Cldr.JE

        Evergreen.V37.Cldr.JM ->
            Evergreen.V42.Cldr.JM

        Evergreen.V37.Cldr.JO ->
            Evergreen.V42.Cldr.JO

        Evergreen.V37.Cldr.JP ->
            Evergreen.V42.Cldr.JP

        Evergreen.V37.Cldr.KE ->
            Evergreen.V42.Cldr.KE

        Evergreen.V37.Cldr.KG ->
            Evergreen.V42.Cldr.KG

        Evergreen.V37.Cldr.KH ->
            Evergreen.V42.Cldr.KH

        Evergreen.V37.Cldr.KI ->
            Evergreen.V42.Cldr.KI

        Evergreen.V37.Cldr.KM ->
            Evergreen.V42.Cldr.KM

        Evergreen.V37.Cldr.KN ->
            Evergreen.V42.Cldr.KN

        Evergreen.V37.Cldr.KP ->
            Evergreen.V42.Cldr.KP

        Evergreen.V37.Cldr.KR ->
            Evergreen.V42.Cldr.KR

        Evergreen.V37.Cldr.KW ->
            Evergreen.V42.Cldr.KW

        Evergreen.V37.Cldr.KY ->
            Evergreen.V42.Cldr.KY

        Evergreen.V37.Cldr.KZ ->
            Evergreen.V42.Cldr.KZ

        Evergreen.V37.Cldr.LA ->
            Evergreen.V42.Cldr.LA

        Evergreen.V37.Cldr.LB ->
            Evergreen.V42.Cldr.LB

        Evergreen.V37.Cldr.LC ->
            Evergreen.V42.Cldr.LC

        Evergreen.V37.Cldr.LI ->
            Evergreen.V42.Cldr.LI

        Evergreen.V37.Cldr.LK ->
            Evergreen.V42.Cldr.LK

        Evergreen.V37.Cldr.LR ->
            Evergreen.V42.Cldr.LR

        Evergreen.V37.Cldr.LS ->
            Evergreen.V42.Cldr.LS

        Evergreen.V37.Cldr.LT_ ->
            Evergreen.V42.Cldr.LT_

        Evergreen.V37.Cldr.LU ->
            Evergreen.V42.Cldr.LU

        Evergreen.V37.Cldr.LV ->
            Evergreen.V42.Cldr.LV

        Evergreen.V37.Cldr.LY ->
            Evergreen.V42.Cldr.LY

        Evergreen.V37.Cldr.MA ->
            Evergreen.V42.Cldr.MA

        Evergreen.V37.Cldr.MC ->
            Evergreen.V42.Cldr.MC

        Evergreen.V37.Cldr.MD ->
            Evergreen.V42.Cldr.MD

        Evergreen.V37.Cldr.ME ->
            Evergreen.V42.Cldr.ME

        Evergreen.V37.Cldr.MF ->
            Evergreen.V42.Cldr.MF

        Evergreen.V37.Cldr.MG ->
            Evergreen.V42.Cldr.MG

        Evergreen.V37.Cldr.MH ->
            Evergreen.V42.Cldr.MH

        Evergreen.V37.Cldr.MK ->
            Evergreen.V42.Cldr.MK

        Evergreen.V37.Cldr.ML ->
            Evergreen.V42.Cldr.ML

        Evergreen.V37.Cldr.MM ->
            Evergreen.V42.Cldr.MM

        Evergreen.V37.Cldr.MN ->
            Evergreen.V42.Cldr.MN

        Evergreen.V37.Cldr.MO ->
            Evergreen.V42.Cldr.MO

        Evergreen.V37.Cldr.MP ->
            Evergreen.V42.Cldr.MP

        Evergreen.V37.Cldr.MQ ->
            Evergreen.V42.Cldr.MQ

        Evergreen.V37.Cldr.MR ->
            Evergreen.V42.Cldr.MR

        Evergreen.V37.Cldr.MS ->
            Evergreen.V42.Cldr.MS

        Evergreen.V37.Cldr.MT ->
            Evergreen.V42.Cldr.MT

        Evergreen.V37.Cldr.MU ->
            Evergreen.V42.Cldr.MU

        Evergreen.V37.Cldr.MV ->
            Evergreen.V42.Cldr.MV

        Evergreen.V37.Cldr.MW ->
            Evergreen.V42.Cldr.MW

        Evergreen.V37.Cldr.MX ->
            Evergreen.V42.Cldr.MX

        Evergreen.V37.Cldr.MY ->
            Evergreen.V42.Cldr.MY

        Evergreen.V37.Cldr.MZ ->
            Evergreen.V42.Cldr.MZ

        Evergreen.V37.Cldr.NA ->
            Evergreen.V42.Cldr.NA

        Evergreen.V37.Cldr.NC ->
            Evergreen.V42.Cldr.NC

        Evergreen.V37.Cldr.NE ->
            Evergreen.V42.Cldr.NE

        Evergreen.V37.Cldr.NF ->
            Evergreen.V42.Cldr.NF

        Evergreen.V37.Cldr.NG ->
            Evergreen.V42.Cldr.NG

        Evergreen.V37.Cldr.NI ->
            Evergreen.V42.Cldr.NI

        Evergreen.V37.Cldr.NL ->
            Evergreen.V42.Cldr.NL

        Evergreen.V37.Cldr.NO ->
            Evergreen.V42.Cldr.NO

        Evergreen.V37.Cldr.NP ->
            Evergreen.V42.Cldr.NP

        Evergreen.V37.Cldr.NR ->
            Evergreen.V42.Cldr.NR

        Evergreen.V37.Cldr.NU ->
            Evergreen.V42.Cldr.NU

        Evergreen.V37.Cldr.NZ ->
            Evergreen.V42.Cldr.NZ

        Evergreen.V37.Cldr.OM ->
            Evergreen.V42.Cldr.OM

        Evergreen.V37.Cldr.PA ->
            Evergreen.V42.Cldr.PA

        Evergreen.V37.Cldr.PE ->
            Evergreen.V42.Cldr.PE

        Evergreen.V37.Cldr.PF ->
            Evergreen.V42.Cldr.PF

        Evergreen.V37.Cldr.PG ->
            Evergreen.V42.Cldr.PG

        Evergreen.V37.Cldr.PH ->
            Evergreen.V42.Cldr.PH

        Evergreen.V37.Cldr.PK ->
            Evergreen.V42.Cldr.PK

        Evergreen.V37.Cldr.PL ->
            Evergreen.V42.Cldr.PL

        Evergreen.V37.Cldr.PM ->
            Evergreen.V42.Cldr.PM

        Evergreen.V37.Cldr.PN ->
            Evergreen.V42.Cldr.PN

        Evergreen.V37.Cldr.PR ->
            Evergreen.V42.Cldr.PR

        Evergreen.V37.Cldr.PS ->
            Evergreen.V42.Cldr.PS

        Evergreen.V37.Cldr.PT ->
            Evergreen.V42.Cldr.PT

        Evergreen.V37.Cldr.PW ->
            Evergreen.V42.Cldr.PW

        Evergreen.V37.Cldr.PY ->
            Evergreen.V42.Cldr.PY

        Evergreen.V37.Cldr.QA ->
            Evergreen.V42.Cldr.QA

        Evergreen.V37.Cldr.RE ->
            Evergreen.V42.Cldr.RE

        Evergreen.V37.Cldr.RO ->
            Evergreen.V42.Cldr.RO

        Evergreen.V37.Cldr.RS ->
            Evergreen.V42.Cldr.RS

        Evergreen.V37.Cldr.RU ->
            Evergreen.V42.Cldr.RU

        Evergreen.V37.Cldr.RW ->
            Evergreen.V42.Cldr.RW

        Evergreen.V37.Cldr.SA ->
            Evergreen.V42.Cldr.SA

        Evergreen.V37.Cldr.SB ->
            Evergreen.V42.Cldr.SB

        Evergreen.V37.Cldr.SC ->
            Evergreen.V42.Cldr.SC

        Evergreen.V37.Cldr.SD ->
            Evergreen.V42.Cldr.SD

        Evergreen.V37.Cldr.SE ->
            Evergreen.V42.Cldr.SE

        Evergreen.V37.Cldr.SG ->
            Evergreen.V42.Cldr.SG

        Evergreen.V37.Cldr.SH ->
            Evergreen.V42.Cldr.SH

        Evergreen.V37.Cldr.SI ->
            Evergreen.V42.Cldr.SI

        Evergreen.V37.Cldr.SJ ->
            Evergreen.V42.Cldr.SJ

        Evergreen.V37.Cldr.SK ->
            Evergreen.V42.Cldr.SK

        Evergreen.V37.Cldr.SL ->
            Evergreen.V42.Cldr.SL

        Evergreen.V37.Cldr.SM ->
            Evergreen.V42.Cldr.SM

        Evergreen.V37.Cldr.SN ->
            Evergreen.V42.Cldr.SN

        Evergreen.V37.Cldr.SO ->
            Evergreen.V42.Cldr.SO

        Evergreen.V37.Cldr.SR ->
            Evergreen.V42.Cldr.SR

        Evergreen.V37.Cldr.SS ->
            Evergreen.V42.Cldr.SS

        Evergreen.V37.Cldr.ST ->
            Evergreen.V42.Cldr.ST

        Evergreen.V37.Cldr.SV ->
            Evergreen.V42.Cldr.SV

        Evergreen.V37.Cldr.SX ->
            Evergreen.V42.Cldr.SX

        Evergreen.V37.Cldr.SY ->
            Evergreen.V42.Cldr.SY

        Evergreen.V37.Cldr.SZ ->
            Evergreen.V42.Cldr.SZ

        Evergreen.V37.Cldr.TC ->
            Evergreen.V42.Cldr.TC

        Evergreen.V37.Cldr.TD ->
            Evergreen.V42.Cldr.TD

        Evergreen.V37.Cldr.TF ->
            Evergreen.V42.Cldr.TF

        Evergreen.V37.Cldr.TG ->
            Evergreen.V42.Cldr.TG

        Evergreen.V37.Cldr.TH ->
            Evergreen.V42.Cldr.TH

        Evergreen.V37.Cldr.TJ ->
            Evergreen.V42.Cldr.TJ

        Evergreen.V37.Cldr.TK ->
            Evergreen.V42.Cldr.TK

        Evergreen.V37.Cldr.TL ->
            Evergreen.V42.Cldr.TL

        Evergreen.V37.Cldr.TM ->
            Evergreen.V42.Cldr.TM

        Evergreen.V37.Cldr.TN ->
            Evergreen.V42.Cldr.TN

        Evergreen.V37.Cldr.TO ->
            Evergreen.V42.Cldr.TO

        Evergreen.V37.Cldr.TR ->
            Evergreen.V42.Cldr.TR

        Evergreen.V37.Cldr.TT ->
            Evergreen.V42.Cldr.TT

        Evergreen.V37.Cldr.TV ->
            Evergreen.V42.Cldr.TV

        Evergreen.V37.Cldr.TW ->
            Evergreen.V42.Cldr.TW

        Evergreen.V37.Cldr.TZ ->
            Evergreen.V42.Cldr.TZ

        Evergreen.V37.Cldr.UA ->
            Evergreen.V42.Cldr.UA

        Evergreen.V37.Cldr.UG ->
            Evergreen.V42.Cldr.UG

        Evergreen.V37.Cldr.UM ->
            Evergreen.V42.Cldr.UM

        Evergreen.V37.Cldr.US ->
            Evergreen.V42.Cldr.US

        Evergreen.V37.Cldr.UY ->
            Evergreen.V42.Cldr.UY

        Evergreen.V37.Cldr.UZ ->
            Evergreen.V42.Cldr.UZ

        Evergreen.V37.Cldr.VA ->
            Evergreen.V42.Cldr.VA

        Evergreen.V37.Cldr.VC ->
            Evergreen.V42.Cldr.VC

        Evergreen.V37.Cldr.VE ->
            Evergreen.V42.Cldr.VE

        Evergreen.V37.Cldr.VG ->
            Evergreen.V42.Cldr.VG

        Evergreen.V37.Cldr.VI ->
            Evergreen.V42.Cldr.VI

        Evergreen.V37.Cldr.VN ->
            Evergreen.V42.Cldr.VN

        Evergreen.V37.Cldr.VU ->
            Evergreen.V42.Cldr.VU

        Evergreen.V37.Cldr.WF ->
            Evergreen.V42.Cldr.WF

        Evergreen.V37.Cldr.WS ->
            Evergreen.V42.Cldr.WS

        Evergreen.V37.Cldr.XK ->
            Evergreen.V42.Cldr.XK

        Evergreen.V37.Cldr.YE ->
            Evergreen.V42.Cldr.YE

        Evergreen.V37.Cldr.YT ->
            Evergreen.V42.Cldr.YT

        Evergreen.V37.Cldr.ZA ->
            Evergreen.V42.Cldr.ZA

        Evergreen.V37.Cldr.ZM ->
            Evergreen.V42.Cldr.ZM

        Evergreen.V37.Cldr.ZW ->
            Evergreen.V42.Cldr.ZW


migrate_Main_Msg : Evergreen.V37.Main.Msg -> Evergreen.V42.Main.Msg
migrate_Main_Msg old =
    case old of
        Evergreen.V37.Main.UrlRequested p0 ->
            Evergreen.V42.Main.UrlRequested p0

        Evergreen.V37.Main.UrlChanged p0 ->
            Evergreen.V42.Main.UrlChanged p0

        Evergreen.V37.Main.Page p0 ->
            Evergreen.V42.Main.Page (p0 |> migrate_Main_Pages_Msg_Msg)

        Evergreen.V37.Main.Layout p0 ->
            Evergreen.V42.Main.Layout p0

        Evergreen.V37.Main.Shared p0 ->
            Evergreen.V42.Main.Shared (p0 |> migrate_Shared_Msg)

        Evergreen.V37.Main.Batch p0 ->
            Evergreen.V42.Main.Batch (p0 |> List.map migrate_Main_Msg)


migrate_Main_Pages_Model_Model : Evergreen.V37.Main.Pages.Model.Model -> Evergreen.V42.Main.Pages.Model.Model
migrate_Main_Pages_Model_Model old =
    case old of
        Evergreen.V37.Main.Pages.Model.Home_ p0 ->
            Evergreen.V42.Main.Pages.Model.Home_ (p0 |> migrate_Pages_Home__Model)

        Evergreen.V37.Main.Pages.Model.Finished p0 ->
            Evergreen.V42.Main.Pages.Model.Finished p0

        Evergreen.V37.Main.Pages.Model.Play p0 ->
            Evergreen.V42.Main.Pages.Model.Play (p0 |> migrate_Pages_Play_Model)

        Evergreen.V37.Main.Pages.Model.Sort p0 ->
            Evergreen.V42.Main.Pages.Model.Sort (p0 |> migrate_Pages_Sort_Model)

        Evergreen.V37.Main.Pages.Model.NotFound_ p0 ->
            Evergreen.V42.Main.Pages.Model.NotFound_ (p0 |> migrate_Pages_NotFound__Model)

        Evergreen.V37.Main.Pages.Model.Redirecting_ ->
            Evergreen.V42.Main.Pages.Model.Redirecting_

        Evergreen.V37.Main.Pages.Model.Loading_ ->
            Evergreen.V42.Main.Pages.Model.Loading_


migrate_Main_Pages_Msg_Msg : Evergreen.V37.Main.Pages.Msg.Msg -> Evergreen.V42.Main.Pages.Msg.Msg
migrate_Main_Pages_Msg_Msg old =
    case old of
        Evergreen.V37.Main.Pages.Msg.Home_ p0 ->
            Evergreen.V42.Main.Pages.Msg.Home_ (p0 |> migrate_Pages_Home__Msg)

        Evergreen.V37.Main.Pages.Msg.Finished p0 ->
            Evergreen.V42.Main.Pages.Msg.Finished (p0 |> migrate_Pages_Finished_Msg)

        Evergreen.V37.Main.Pages.Msg.Play p0 ->
            Evergreen.V42.Main.Pages.Msg.Play (p0 |> migrate_Pages_Play_Msg)

        Evergreen.V37.Main.Pages.Msg.Sort p0 ->
            Evergreen.V42.Main.Pages.Msg.Sort (p0 |> migrate_Pages_Sort_Msg)

        Evergreen.V37.Main.Pages.Msg.NotFound_ p0 ->
            Evergreen.V42.Main.Pages.Msg.NotFound_ (p0 |> migrate_Pages_NotFound__Msg)


migrate_Pages_Finished_Msg : Evergreen.V37.Pages.Finished.Msg -> Evergreen.V42.Pages.Finished.Msg
migrate_Pages_Finished_Msg old =
    case old of
        Evergreen.V37.Pages.Finished.Play ->
            Evergreen.V42.Pages.Finished.Play


migrate_Pages_Home__Model : Evergreen.V37.Pages.Home_.Model -> Evergreen.V42.Pages.Home_.Model
migrate_Pages_Home__Model old =
    old


migrate_Pages_Home__Msg : Evergreen.V37.Pages.Home_.Msg -> Evergreen.V42.Pages.Home_.Msg
migrate_Pages_Home__Msg old =
    case old of
        Evergreen.V37.Pages.Home_.Play ->
            Evergreen.V42.Pages.Home_.Play

        Evergreen.V37.Pages.Home_.ChangeOptions p0 ->
            Evergreen.V42.Pages.Home_.ChangeOptions (p0 |> migrate_Shared_Model_GameOptions)

        Evergreen.V37.Pages.Home_.ChangingLocale p0 ->
            Evergreen.V42.Pages.Home_.ChangingLocale p0

        Evergreen.V37.Pages.Home_.Locale p0 ->
            Evergreen.V42.Pages.Home_.Locale p0


migrate_Pages_NotFound__Model : Evergreen.V37.Pages.NotFound_.Model -> Evergreen.V42.Pages.NotFound_.Model
migrate_Pages_NotFound__Model old =
    old


migrate_Pages_NotFound__Msg : Evergreen.V37.Pages.NotFound_.Msg -> Evergreen.V42.Pages.NotFound_.Msg
migrate_Pages_NotFound__Msg old =
    case old of
        Evergreen.V37.Pages.NotFound_.ExampleMsgReplaceMe ->
            Evergreen.V42.Pages.NotFound_.ExampleMsgReplaceMe


migrate_Pages_Play_InnerModel : Evergreen.V37.Pages.Play.InnerModel -> Evergreen.V42.Pages.Play.InnerModel
migrate_Pages_Play_InnerModel old =
    { current = old.current |> migrate_Shared_Model_Card
    , picked = old.picked |> Maybe.map migrate_Shared_Model_Country
    , queue = old.queue |> List.map migrate_Shared_Model_Card
    , score = old.score
    }


migrate_Pages_Play_Model : Evergreen.V37.Pages.Play.Model -> Evergreen.V42.Pages.Play.Model
migrate_Pages_Play_Model old =
    old |> Maybe.map migrate_Pages_Play_InnerModel


migrate_Pages_Play_Msg : Evergreen.V37.Pages.Play.Msg -> Evergreen.V42.Pages.Play.Msg
migrate_Pages_Play_Msg old =
    case old of
        Evergreen.V37.Pages.Play.Pick p0 ->
            Evergreen.V42.Pages.Play.Pick (p0 |> migrate_Shared_Model_Country)

        Evergreen.V37.Pages.Play.Next ->
            Evergreen.V42.Pages.Play.Next


migrate_Pages_Sort_Model : Evergreen.V37.Pages.Sort.Model -> Evergreen.V42.Pages.Sort.Model
migrate_Pages_Sort_Model old =
    { groups = old.groups |> List.map (List.map migrate_Shared_Model_Country)
    , selected = old.selected |> Maybe.map migrate_Shared_Model_Country
    }


migrate_Pages_Sort_Msg : Evergreen.V37.Pages.Sort.Msg -> Evergreen.V42.Pages.Sort.Msg
migrate_Pages_Sort_Msg old =
    case old of
        Evergreen.V37.Pages.Sort.Move p0 p1 ->
            Evergreen.V42.Pages.Sort.Move (p0 |> migrate_Shared_Model_Country) p1

        Evergreen.V37.Pages.Sort.SelectForMove p0 ->
            Evergreen.V42.Pages.Sort.SelectForMove (p0 |> migrate_Shared_Model_Country)


migrate_Shared_Model_Card : Evergreen.V37.Shared.Model.Card -> Evergreen.V42.Shared.Model.Card
migrate_Shared_Model_Card old =
    { guessing = old.guessing |> migrate_Shared_Model_Country
    , answers = old.answers |> List.map migrate_Shared_Model_Country
    , guessFrom = old.guessFrom |> migrate_Shared_Model_Property
    , guessTo = old.guessTo |> migrate_Shared_Model_Property
    }


migrate_Shared_Model_Context : Evergreen.V37.Shared.Model.Context -> Evergreen.V42.Shared.Model.Context
migrate_Shared_Model_Context old =
    old


migrate_Shared_Model_Continent : Evergreen.V37.Shared.Model.Continent -> Evergreen.V42.Shared.Model.Continent
migrate_Shared_Model_Continent old =
    case old of
        Evergreen.V37.Shared.Model.Africa ->
            Evergreen.V42.Shared.Model.Africa

        Evergreen.V37.Shared.Model.Antartica ->
            Evergreen.V42.Shared.Model.Antartica

        Evergreen.V37.Shared.Model.Asia ->
            Evergreen.V42.Shared.Model.Asia

        Evergreen.V37.Shared.Model.Europe ->
            Evergreen.V42.Shared.Model.Europe

        Evergreen.V37.Shared.Model.NorthAmerica ->
            Evergreen.V42.Shared.Model.NorthAmerica

        Evergreen.V37.Shared.Model.Oceania ->
            Evergreen.V42.Shared.Model.Oceania

        Evergreen.V37.Shared.Model.SouthAmerica ->
            Evergreen.V42.Shared.Model.SouthAmerica


migrate_Shared_Model_Country : Evergreen.V37.Shared.Model.Country -> Evergreen.V42.Shared.Model.Country
migrate_Shared_Model_Country old =
    case old of
        Evergreen.V37.Shared.Model.Iso3166 p0 ->
            Evergreen.V42.Shared.Model.Iso3166 (p0 |> migrate_Cldr_CountryCode)

        Evergreen.V37.Shared.Model.PartiallyRecognized p0 ->
            Evergreen.V42.Shared.Model.PartiallyRecognized p0


migrate_Shared_Model_Difficulty : Evergreen.V37.Shared.Model.Difficulty -> Evergreen.V42.Shared.Model.Difficulty
migrate_Shared_Model_Difficulty old =
    case old of
        Evergreen.V37.Shared.Model.Easy ->
            Evergreen.V42.Shared.Model.Easy

        Evergreen.V37.Shared.Model.Normal ->
            Evergreen.V42.Shared.Model.Normal

        Evergreen.V37.Shared.Model.Hard ->
            Evergreen.V42.Shared.Model.Hard


migrate_Shared_Model_GameOptions : Evergreen.V37.Shared.Model.GameOptions -> Evergreen.V42.Shared.Model.GameOptions
migrate_Shared_Model_GameOptions old =
    { gameLength = old.gameLength
    , difficulty = old.difficulty |> migrate_Shared_Model_Difficulty
    , answersPerCard = old.answersPerCard
    , guessPatterns = old.guessPatterns |> List.map (Tuple.mapBoth migrate_Shared_Model_Property migrate_Shared_Model_Property)
    , sovereignOnly = old.sovereignOnly
    , continents = old.continents |> List.map migrate_Shared_Model_Continent
    }


migrate_Shared_Model_Property : Evergreen.V37.Shared.Model.Property -> Evergreen.V42.Shared.Model.Property
migrate_Shared_Model_Property old =
    case old of
        Evergreen.V37.Shared.Model.Flag ->
            Evergreen.V42.Shared.Model.Flag

        Evergreen.V37.Shared.Model.Name ->
            Evergreen.V42.Shared.Model.Name


migrate_Shared_Msg : Evergreen.V37.Shared.Msg -> Evergreen.V42.Shared.Msg
migrate_Shared_Msg old =
    old |> migrate_Shared_Msg_Msg


migrate_Shared_Msg_Msg : Evergreen.V37.Shared.Msg.Msg -> Evergreen.V42.Shared.Msg.Msg
migrate_Shared_Msg_Msg old =
    case old of
        Evergreen.V37.Shared.Msg.Seed p0 ->
            Evergreen.V42.Shared.Msg.Seed p0

        Evergreen.V37.Shared.Msg.Locale p0 ->
            Evergreen.V42.Shared.Msg.Locale p0

        Evergreen.V37.Shared.Msg.ChangeOptions p0 ->
            Evergreen.V42.Shared.Msg.ChangeOptions (p0 |> migrate_Shared_Model_GameOptions)

        Evergreen.V37.Shared.Msg.Play ->
            Evergreen.V42.Shared.Msg.Play

        Evergreen.V37.Shared.Msg.Finished p0 ->
            Evergreen.V42.Shared.Msg.Finished p0

        Evergreen.V37.Shared.Msg.Nop ->
            Evergreen.V42.Shared.Msg.Nop
