module Evergreen.Migrate.V6 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V4.Types
import Evergreen.V6.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V4.Types.FrontendModel -> ModelMigration Evergreen.V6.Types.FrontendModel Evergreen.V6.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V4.Types.BackendModel -> ModelMigration Evergreen.V6.Types.BackendModel Evergreen.V6.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V4.Types.FrontendMsg -> MsgMigration Evergreen.V6.Types.FrontendMsg Evergreen.V6.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V4.Types.ToBackend -> MsgMigration Evergreen.V6.Types.ToBackend Evergreen.V6.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V4.Types.BackendMsg -> MsgMigration Evergreen.V6.Types.BackendMsg Evergreen.V6.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V4.Types.ToFrontend -> MsgMigration Evergreen.V6.Types.ToFrontend Evergreen.V6.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_Context : Evergreen.V4.Types.Context -> Evergreen.V6.Types.Context
migrate_Types_Context old =
    { language = old.language |> migrate_Types_Language
    }


migrate_Types_Language : Evergreen.V4.Types.Language -> Evergreen.V6.Types.Language
migrate_Types_Language old =
    case old of
        Evergreen.V4.Types.Arabic ->
            Evergreen.V6.Types.Arabic

        Evergreen.V4.Types.Chinese ->
            Evergreen.V6.Types.Chinese

        Evergreen.V4.Types.Czech ->
            Evergreen.V6.Types.Czech

        Evergreen.V4.Types.Danish ->
            Evergreen.V6.Types.Danish

        Evergreen.V4.Types.Dutch ->
            Evergreen.V6.Types.Dutch

        Evergreen.V4.Types.English ->
            Evergreen.V6.Types.English

        Evergreen.V4.Types.Estonian ->
            Evergreen.V6.Types.Estonian

        Evergreen.V4.Types.French ->
            Evergreen.V6.Types.French

        Evergreen.V4.Types.German ->
            Evergreen.V6.Types.German

        Evergreen.V4.Types.Greek ->
            Evergreen.V6.Types.Greek

        Evergreen.V4.Types.Hungarian ->
            Evergreen.V6.Types.Hungarian

        Evergreen.V4.Types.Italian ->
            Evergreen.V6.Types.Italian

        Evergreen.V4.Types.Japanese ->
            Evergreen.V6.Types.Japanese

        Evergreen.V4.Types.Lithuanian ->
            Evergreen.V6.Types.Lithuanian

        Evergreen.V4.Types.Norwegian ->
            Evergreen.V6.Types.Norwegian

        Evergreen.V4.Types.Polish ->
            Evergreen.V6.Types.Polish

        Evergreen.V4.Types.Portuguese ->
            Evergreen.V6.Types.Portuguese

        Evergreen.V4.Types.Romanian ->
            Evergreen.V6.Types.Romanian

        Evergreen.V4.Types.Russian ->
            Evergreen.V6.Types.Russian

        Evergreen.V4.Types.Slovak ->
            Evergreen.V6.Types.Slovak

        Evergreen.V4.Types.Spanish ->
            Evergreen.V6.Types.Spanish

        Evergreen.V4.Types.Thai ->
            Evergreen.V6.Types.Thai

        Evergreen.V4.Types.Ukrainian ->
            Evergreen.V6.Types.Ukrainian


migrate_Types_SortingModel : Evergreen.V4.Types.SortingModel -> Evergreen.V6.Types.SortingModel
migrate_Types_SortingModel old =
    old
