module Translations exposing (I18n, Language(..), africa, antarctica, asia, change, continents, currentLanguage, difficulty, easy, europe, finalScore, flag, gameLanguage, gameLength, guess, hard, include, init, languageFromString, languageToString, languages, load, name, next, normal, northAmerica, oceania, play, playAgain, possibleAnswers, score, search, southAmerica, states, statesAndTerritories, title)

{-| This file was generated by travelm-agency version 3.8.0.

If you have any issues with the generated code, do not hesitate to open an issue here: <https://github.com/andreasewering/travelm-agency/issues>

-}

import List
import Maybe
import String


{-| Initialize an i18n instance based on a language
-}
init : Language -> I18n
init =
    I18n


{-| Get the currently active language.
-}
currentLanguage : I18n -> Language
currentLanguage (I18n lang) =
    lang


{-| Switch to another i18n instance based on a language
-}
load : Language -> I18n -> I18n
load lang _ =
    init lang


type I18n
    = I18n Language


africa : I18n -> String
africa (I18n lang) =
    case lang of
        De ->
            "Afrika"

        En ->
            "Africa"

        It ->
            "Africa"

        Nl ->
            "Afrika"

        Sv ->
            "Afrika"


antarctica : I18n -> String
antarctica (I18n lang) =
    case lang of
        De ->
            "Antarktis"

        En ->
            "Antarctica"

        It ->
            "Antartide"

        Nl ->
            "Antarctica"

        Sv ->
            "Antarktis"


asia : I18n -> String
asia (I18n lang) =
    case lang of
        De ->
            "Asien"

        En ->
            "Asia"

        It ->
            "Asia"

        Nl ->
            "Azië"

        Sv ->
            "Asien"


change : I18n -> String
change (I18n lang) =
    case lang of
        De ->
            "Ändern"

        En ->
            "Change"

        It ->
            "Cambia"

        Nl ->
            "Aanpassen"

        Sv ->
            "Byt"


continents : I18n -> String
continents (I18n lang) =
    case lang of
        De ->
            "Kontinente"

        En ->
            "Continents"

        It ->
            "Continenti"

        Nl ->
            "Continenten"

        Sv ->
            "Kontinenter"


difficulty : I18n -> String
difficulty (I18n lang) =
    case lang of
        De ->
            "Schwierigkeitsgrad"

        En ->
            "Difficulty"

        It ->
            "Difficoltà"

        Nl ->
            "Moeilijkheid"

        Sv ->
            "Svårighetsgrad"


easy : I18n -> String
easy (I18n lang) =
    case lang of
        De ->
            "Einfach"

        En ->
            "Easy"

        It ->
            "Facile"

        Nl ->
            "Makkelijk"

        Sv ->
            "Lätt"


europe : I18n -> String
europe (I18n lang) =
    case lang of
        De ->
            "Europa"

        En ->
            "Europe"

        It ->
            "Europa"

        Nl ->
            "Europa"

        Sv ->
            "Europa"


finalScore : { points : String, total : String } -> I18n -> String
finalScore data (I18n lang) =
    case lang of
        De ->
            "Finaler Punktestand: " ++ data.points ++ "/" ++ data.total

        En ->
            "Final score: " ++ data.points ++ "/" ++ data.total

        It ->
            "Punteggio finale: " ++ data.points ++ "/" ++ data.total

        Nl ->
            "Eind score: " ++ data.points ++ "/" ++ data.total

        Sv ->
            "Slutresultat: " ++ data.points ++ "/" ++ data.total


flag : I18n -> String
flag (I18n lang) =
    case lang of
        De ->
            "Flagge"

        En ->
            "Flag"

        It ->
            "Bandiera"

        Nl ->
            "Vlag"

        Sv ->
            "Flagga"


gameLanguage : I18n -> String
gameLanguage (I18n lang) =
    case lang of
        De ->
            "Spielsprache"

        En ->
            "Game Language"

        It ->
            "Lingua"

        Nl ->
            "Spel Taal"

        Sv ->
            "Spelspråk"


gameLength : I18n -> String
gameLength (I18n lang) =
    case lang of
        De ->
            "Spiellänge"

        En ->
            "Game Length"

        It ->
            "Lunghezza partita"

        Nl ->
            "Spel Lengte"

        Sv ->
            "Spellängd"


guess : I18n -> String
guess (I18n lang) =
    case lang of
        De ->
            "Errate"

        En ->
            "Guess"

        It ->
            "Indovina"

        Nl ->
            "Raden"

        Sv ->
            "Gissa"


hard : I18n -> String
hard (I18n lang) =
    case lang of
        De ->
            "Schwer"

        En ->
            "Hard"

        It ->
            "Difficile"

        Nl ->
            "Moeilijk"

        Sv ->
            "Svår"


include : I18n -> String
include (I18n lang) =
    case lang of
        De ->
            "Inkludiere"

        En ->
            "Include"

        It ->
            "Includi"

        Nl ->
            "Categorieën"

        Sv ->
            "Inkludera"


name : I18n -> String
name (I18n lang) =
    case lang of
        De ->
            "Name"

        En ->
            "Name"

        It ->
            "Nome"

        Nl ->
            "Naam"

        Sv ->
            "Namn"


next : I18n -> String
next (I18n lang) =
    case lang of
        De ->
            "Weiter"

        En ->
            "Next"

        It ->
            "Avanti"

        Nl ->
            "Volgende"

        Sv ->
            "Nästa"


normal : I18n -> String
normal (I18n lang) =
    case lang of
        De ->
            "Normal"

        En ->
            "Normal"

        It ->
            "Normale"

        Nl ->
            "Normaal"

        Sv ->
            "Normal"


northAmerica : I18n -> String
northAmerica (I18n lang) =
    case lang of
        De ->
            "Nordamerika"

        En ->
            "North America"

        It ->
            "Nord America"

        Nl ->
            "Noord Amerika"

        Sv ->
            "Nordamerika"


oceania : I18n -> String
oceania (I18n lang) =
    case lang of
        De ->
            "Ozeanien"

        En ->
            "Oceania"

        It ->
            "Oceania"

        Nl ->
            "Oceanië"

        Sv ->
            "Oceanien"


play : I18n -> String
play (I18n lang) =
    case lang of
        De ->
            "Spielen"

        En ->
            "Play"

        It ->
            "Gioca"

        Nl ->
            "Start"

        Sv ->
            "Spela"


playAgain : I18n -> String
playAgain (I18n lang) =
    case lang of
        De ->
            "Nochmal abspielen"

        En ->
            "Play again"

        It ->
            "Gioca di nuovo"

        Nl ->
            "Speel opnieuw"

        Sv ->
            "Spela igen"


possibleAnswers : I18n -> String
possibleAnswers (I18n lang) =
    case lang of
        De ->
            "Mögliche Antworten"

        En ->
            "Possible answers"

        It ->
            "Opzioni"

        Nl ->
            "Mogelijke antwoorden"

        Sv ->
            "Möjliga svar"


score : String -> I18n -> String
score score__ (I18n lang) =
    case lang of
        De ->
            "Punktestand: " ++ score__

        En ->
            "Score: " ++ score__

        It ->
            "Punteggio: " ++ score__

        Nl ->
            "Score: " ++ score__

        Sv ->
            "Poäng: " ++ score__


search : I18n -> String
search (I18n lang) =
    case lang of
        De ->
            "Suche"

        En ->
            "Search"

        It ->
            "Cerca"

        Nl ->
            "Zoeken"

        Sv ->
            "Sök"


southAmerica : I18n -> String
southAmerica (I18n lang) =
    case lang of
        De ->
            "Südamerika"

        En ->
            "South America"

        It ->
            "Sud America"

        Nl ->
            "Zuid Amerika"

        Sv ->
            "Sydamerika"


states : I18n -> String
states (I18n lang) =
    case lang of
        De ->
            "Staaten"

        En ->
            "States"

        It ->
            "Nazioni"

        Nl ->
            "Staten"

        Sv ->
            "Länder"


statesAndTerritories : I18n -> String
statesAndTerritories (I18n lang) =
    case lang of
        De ->
            "Staaten und Territorien"

        En ->
            "States and territories"

        It ->
            "Nazioni e territori"

        Nl ->
            "Staten en territoria"

        Sv ->
            "Länder och Territorium"


title : I18n -> String
title (I18n lang) =
    case lang of
        De ->
            "Flaggenspiel"

        En ->
            "Flag game"

        It ->
            "Indovina la bandiera"

        Nl ->
            "Vlaggenspel"

        Sv ->
            "Flaggspel"


{-| Enumeration of the supported languages
-}
type Language
    = De
    | En
    | It
    | Nl
    | Sv


{-| A list containing all `Language`s. The list is sorted alphabetically.
-}
languages : List Language
languages =
    [ De, En, It, Nl, Sv ]


{-| Convert a `Language` to its `String` representation.
-}
languageToString : Language -> String
languageToString lang =
    case lang of
        De ->
            "de"

        En ->
            "en"

        It ->
            "it"

        Nl ->
            "nl"

        Sv ->
            "sv"


{-| Maybe parse a `Language` from a `String`.
This will map languages based on the prefix i.e. 'en-US' and 'en' will both map to 'En' unless you provided a 'en-US' translation file.
-}
languageFromString : String -> Maybe Language
languageFromString lang =
    let
        helper langs =
            case langs of
                [] ->
                    Maybe.Nothing

                l :: ls ->
                    if String.startsWith (languageToString l) lang then
                        Maybe.Just l

                    else
                        helper ls
    in
    helper (List.reverse languages)
